### ISSUE TITLE
Specify globals in --env-vars file

### ISSUE THREAD

**Issue by terlar** [aws/aws-sam-cli#1045]
### Describe your idea/feature/enhancement

I wish SAM CLI JSON file provided by `--env-vars` had support for globals. In our `template.yaml` we specify certain environment variables via `Globals: Function: Environment: Variables`. It would be nice if such shared variables could be added in one place inside the JSON file you can provide to `--env-vars`. Currently as far as I understand it you can only specify env vars per function in this file.

### Proposal

Add something like `Globals`, `Function` or similar to the JSON file. What do you think? Any other workarounds? Now I frequently get caught in missing specifying this thing when adding a new function as I rely on the globals for that in the regular template.

**Comment by mnapoli** [comment]
@terlar I tested this and it worked:

```json
{
    "Parameters": {
        "BAR": "helloworld"
    }
}
```

That seems to define the `BAR` environment variable for all functions.

**Comment by jfuss** [comment]
@terlar Thanks for the issue. You can achieve this though the option @mnapoli has shown. We currently support two formats but you cannot intermix them. So if two functions have the same Env Var but you wanted different values, you would need to specify with the LogicalIds instead of Parameters. Marking this as a feature request as I can see some use-cases where it could be beneficial to have some kind of mixed format.

[Here](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/local/lib/local_lambda.py#L175) is the spot in the code where we parse the env vars file contents.

**Comment by pwrmiller** [comment]
Can this be issue be modified to be a documentation change? Specifically, [this section](https://github.com/awslabs/aws-sam-cli/blob/develop/docs/advanced_usage.md) of documentation needs to document the `Parameters` option.

**Comment by ozbillwang** [comment]
Seems `--env-vars` is only available for `sam local invoke`, not for `sam deploy`. 

Could we have the same for `sam deploy` command? So I can easily manage the parameter overrides with a readible Json file.

**Comment by qingchm** [comment]
@ozbillwang To understand the requirement here, the --env-vars option is provided because invoke happens inside a container. Same for build inside containers we support --container-env-var-file option. If you want to use env vars for deploy what's blocking you from directly setting the env vars and reading it? Deploy does not create an isolated execution environment AFAIK

**Comment by qingchm** [comment]
This is still a relevant feature request and we will surely discuss about this. Since our build already integrates both the parameters way and the resource specific way together in one file, this shouldn't be hard to realize as well. Let us check on if we have any concerns supporting this! (build reference: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html#serverless-sam-cli-using-container-environment-file)

**Comment by mildaniel** [comment]
A fix has been released in version 1.56.0 on 09/01. Closing this issue, please re-open if it persists.

**Comment by ozbillwang** [comment]
@qingchm 

Use case is, the environment should be consistent across all sub-commands, when we run local invoke or deployment, we can read the same `--env-vars`

and could you please confirm if this feature is still locked to `build`, not `deploy`?
