### ISSUE TITLE
a faster way to invoke functions without rebuilding, when no dependencies have changed

### ISSUE THREAD

**Issue by radix** [aws/aws-sam-cli#1174]
### Describe your idea/feature/enhancement

If I'm developing a SAM app that uses dependencies (e.g. a requirements.txt file), I have to use `sam build` to ensure those dependencies are included in my package.

However, this also requires me to re-run `sam build` for every code change. This `build` step can take a significant amount of time, even when I haven't changed any dependencies.

I would love it if SAM provided some mechanism to invoke my lambda functions with updated code, but WITHOUT needing to rebuild my package.

### Proposal

The UX is variable, but I can imagine some different possibilites:

1. somehow the `sam build` command could detect whether dependencies have changed, and if not, short-circuit the build process to only update the source code.
2. alternatively, an explicit UX for running my lambdas with updated code. Perhaps a way to mount my source code as a volume in the SAM docker container?

**Comment by CGreenburg** [comment]
I like the idea of checking if dependencies have changed. This could be accomplished by storing a hash of the dependency file (e.g. requirements.txt) somewhere in the `.aws-sam` build directory and using that to determine if dependency installation is necessary or not.

**Comment by mndeveci** [comment]
With the [1.9.0 release](https://github.com/aws/aws-sam-cli/releases/tag/v1.9.0), SAM CLI now supports builds with caching enabled. I will still keep this open as a feature request since this is only related to package dependencies.

**Comment by qingchm** [comment]
@radix Hey a very late update, but starting from release https://github.com/aws/aws-sam-cli/releases/tag/v1.53.0 we do support cached build to separate out dependencies and code, that means we will not be rebuilding code if no updates are onto the dependencies. Furthermore sam sync is a new command that helps you with deploying faster when there are no dependency changes, with sync we create layers for dependencies, and will only update code through sync --code if no dependencies have changes! Closing the issue now since I believe this will suit your need, let me know if you have any feedbacks on this feature!
