### ISSUE TITLE
Sam local invoke does not respect max timeout

### ISSUE THREAD

**Issue by sriram-mv** [aws/aws-sam-cli#1762]
### Description 

Timeout specified in the template during local invoke can be higher than lambda's allowed timeout. This results in failures during deployment, but does not raise any issues when just running `sam local invoke`.

### Steps to reproduce
* Set Timeout to be greater than 900
* try to deploy the lambda via SAM CLI

Provide steps to replicate.

### Observed result

Please provide command output with `--debug` flag set.

``
1 validation error detected: Value '1200' at
'timeout' failed to satisfy constraint: Member
must have value less than or equal to 900
(Service: AWSLambdaInternal; Status Code: 400;
Error Code: ValidationException; Request ID:
d390d311-3fac-4dc2-90f5-3770cfae8c64)
``

### Expected result

* sam local invoke should also enforce this timeout.

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`: 0.40.0

`Add --debug flag to command you are running`

**Comment by awood45** [comment]
I actually do not think we should do this, for forward compatibility reasons.

The issue here is, if AWS Lambda increases the maximum timeout, local invokes would continue to break. Server side validation for this seems appropriate, and given that there isn't a programmatic way for the SAM CLI to determine the max timeout, failing upon deployment to me actually seems correct.

**Comment by MichaelMarner** [comment]
Another reason _not_ to implement this is sometimes it's useful to get an idea of just how long a lambda execution will take, even if it's outside the limits of AWS.

For example, I'm using Lambda to generate a video, stitching images together. It's really useful to be able to run this locally without the limits enforced, so that we can get an idea of the RAM usage and execution time. Even if it's outside the valid range, knowing that we're close means we can optimise, or if we are way beyond the AWS limits, we'd need to come up with a different approach.

**Comment by bobobox** [comment]
Just wanted to say that NOT having the 900s limit enforced locally totally saved our butts today - we have a complex operation handled by a lambda function that normally completes in several minutes but due to a combination of scaling issues and a resulting pileup of changes it needed to deploy, it was taking over 15 minutes, and so failing every time. We were able to do a local invoke and get unblocked with minimal fuss and risk.
