### ISSUE TITLE
SAM CLI deploy should upload package once for all the Lambda functions (Java)

### ISSUE THREAD

**Issue by pradeepvenkataraman** [aws/aws-sam-cli#1910]
Currently, SAM CLI deploy command packages & uploads the code for each Java lambda function even when they are all belonging to same project, package & class. For a webservice containing 4 methods (GET, POST, PATCH, DELETE) each of which is exposed as Lambda function, SAM CLI creates & uploads 4 packages (1 package for each Lambda function) containing same dependencies & classes.

Package for a Java lambda function with their SDK dependencies comes to anywhere between 7MB to 16MB. For a web service with 4 functions, it consumes between 28MB to 64MB of space as same package is uploaded 4 times. Further, considering the fact that each code change deploys the entire package, a developer deploying a web service (with 10 modifications over the course of a day) will end up consuming 280MB to 640MB of space and 40 S3 requests (10 modifications * 4 functions).

If the SAM CLI can ensure the package upload is done once and all the Lambda functions refer to uploaded package (like we can do in manual configuration), then we will end up saving both S3 requests as well as space.

**Comment by awood45** [comment]
I think this is a good feature request, and one we are also happy to take a PR on. It would seem that if multiple functions share the same CodeUri, for example, this optimization is possible.

**Comment by benkehoe** [comment]
Support for multiple functions sharing the same CodeUri has been open for a long time as #1236, and PRs #1180 and #1695 for this support were refused.

**Comment by jfuss** [comment]
@benkehoe They were not refused because we don't want to support. Please read the reply, copied below:

"We do want to enable this support but this needs further design before we can accept. sam build was built with the assumption that each Lambda Function should have its now artifact. This is why sam build will generate built artifacts in ./.aws-sam/build/<LogicalId>. This PR fundamentally changes this and will need updates to the design doc to ensure we understand the change fully and do not break any exiting customers or tools that generate artifacts in this format already.

For anyone finding this, we would encourage a design doc PR so that we can understand the change before implementing.

Closing this as we cannot accept in the current state."

**Comment by awood45** [comment]
This is resolved in `1.6.2` - functions that have the same CodeUri, runtime, and build metadata are built in groups. Those artifacts are also uploaded via `package` together.
