### ISSUE TITLE
Including local source code directories and files in aws-sam application?

### ISSUE THREAD

**Issue by rileypeterson** [aws/aws-sam-cli#1931]
I would love to draw more attention to my question here:

https://stackoverflow.com/questions/61262977/including-local-source-code-directories-and-files-in-aws-sam

Is there a best practice for including local source in the sam build step?
What's the best way to split my dependencies and source code for my application?

Any answers, relevant examples, or advice would be much appreciated.

**Comment by sriram-mv** [comment]
sam build looks at CodeUri to determine the source dir to build from. your manifest file can also have references to other locations, but this might not work if you are building within the container.

**Comment by jfuss** [comment]
You can use `sam build` with your "Manifest" file to define you dependencies. Then you local source should be defined in the `CodeUri` Property within the template. If you have other dependencies that are local, this will not work within `sam build` but you could use Lambda Layers and define the `ContentUri` to your source. 

Closing, since the question is answered.
