### ISSUE TITLE
Show error message when aws-sam-cli-managed-default CloudFormation stack not in CREATE_COMPLETE status

### ISSUE THREAD

**Issue by pyk** [aws/aws-sam-cli#1940]
### Describe your idea/feature/enhancement

I wish `sam-cli` show error message when there is something wrong in the default cloudformation stack.

Currently if the state of cloudformation stack is not complete it raise an key error, due to the `Outputs` object is not available (#1939).

If `aws-sam-cli-managed-default` CloudFormation stack is in bad state, the subsequent deploy command will always failed.

### Proposal

Show the cloudformation stack error message

**Comment by awood45** [comment]
Guidance to implementers: We should also accept states like `UPDATE_COMPLETE`, and behavior when the stack is in a bad state may have to be set to a helpful error message (if we auto-deleted there is a risk of deleting uploaded code).

**Comment by mndeveci** [comment]
In addition to Alex's comments, the state might look like it is in invalid state (ex: `DELETE_FAILED`) but it is actually healthy.

I accidentally tried to delete my `aws-sam-cli-managed-default` stack and it is now in `DELETE_FAILED` state. Which looks like an invalid one, but it is actually healthy, resources exists, and I can do my deployments. Looking at the [stack status codes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html) it is hard to distinguish healthy stack from unhealthy one.

For that reason, instead of checking state of the stack, I [added validation of some information](https://github.com/awslabs/aws-sam-cli/pull/2171) that we expect from the stack (like, `Tags` and `Outputs` information).

**Comment by mndeveci** [comment]
Released with [SAM CLI v1.2.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.2.0)
