### ISSUE TITLE
Npm permission denied errors on mac slave

### ISSUE THREAD

**Issue by hasanak47** [aws/aws-sam-cli#2288]
we are running Jenkins ios jobs in mac slave machine, this is the first time we set up mac slave machine

we seeing permission denied error while running npm install in the Jenkins console, manually when we try from the mac  machine it does work fine, don't know that is the issue 

![image](https://user-images.githubusercontent.com/37875796/95649368-cbaac400-0afa-11eb-9cc5-006c07de9117.png)

**Comment by jfuss** [comment]
@hasanak47 Are you using SAM CLI to build an npm function? Its not clear by the description if you are running npm install or SAM CLI.

It would seem that on your Jenkins machine, you do not have access to run npm. I would investigate why that is. This doesn't seem related to SAM CLI at the moment, given your system is giving you access denied. 

Closing since this is related to your Jenkins setup not SAM CLI.
