### ISSUE TITLE
CodeDeploy cannot use local filesystem CodeURI

### ISSUE THREAD

**Issue by cdstamper** [aws/aws-sam-cli#2323]
### Describe your idea/feature/enhancement

CodeDeploy seems to fail if the template's CodeURI is anything other than an S3 URI.

I am trying to implement a build system that uses artifacts which are stored on a shared EFS volume (thanks to CodeBuild's new support for attaching EFS volumes to the environment). The idea is that the build, test, and deploy stages would access the various artifacts directly from a shared EFS volume, instead of downloading from S3 for each stage. I am primarily targeting improved performance with this setup.

If CodeDeploy understood local paths, I could instruct it to find my source files in the shared EFS volume instead of in S3. This would reduce unnecessary S3 usage (and presumably improve performance).

I understand that `aws cloudformation package` will convert the local paths to S3 paths, but I'd like to avoid the S3 upload & download between stages.

### Proposal

I suggest that CodeDeploy should be able to parse either a local path OR an S3 URI.

The documentation seems to suggest that CodeURI can already be a local path. So I'm not sure if this is actually a feature request or a bug.

**Comment by awsjeffg** [comment]
Hi Chris / @cdstamper 

This is definitely an interesting idea, however I am closing it today because the feature gap you've described is no related to SAM cli. If in the future CodeDeploy is enhanced to support EFS-sourced via EFS, the Cloudformation and related SAM resource definitions should be changed to reflect this.

I am going to raise this idea with the CodeDeploy internally and close this issue for now. Unfortunately CodeDeploy does not have a public issue tracker that I am aware of.
