### ISSUE TITLE
Deploy `amazon/aws-sam-cli-emulation-image-*` to public ECR

### ISSUE THREAD

**Issue by ryosan-470** [aws/aws-sam-cli#2467]
### Describe your idea/feature/enhancement

I want the SAM emulation image `amazon/aws-sam-cli-emulation-image*-` to be deployed to the [Amazon ECR Public Gallery](https://gallery.ecr.aws/). Because when I run tests (ex `sam local invoke`) in CodeBuild, I run into the [DockerHub image pull limit](https://www.docker.com/increase-rate-limits) and the tests fail.

**Comment by jfuss** [comment]
@ryosan-470 Thanks for the issue. We are still looking into ECR Public as an option.

Side note: Why are you running `sam local invoke` in CI? I would suggest running tests in CI on Lambda directly. There are differences between how docker behaves and AWS Lambda behaves. This could give you a false sense of things working. One example is multi-threading in python works locally but not in Lambda (due to the some directories being available in docker but not in Lambda itself). The `sam local` suite was written to support testing locally for quick debug cycles, not really within CI.

**Comment by ryosan-470** [comment]
@jfuss Thank you for your consideration. I am looking forward to deploying your images at the public ECR.

> Why are you running sam local invoke in CI?

I did NOT know the differences between boths. I want to test it as an integration test in CI so that I used `sam local invoke` and [Integrating with automated tests](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-automated-tests.html) as reference.

**Comment by stowns** [comment]
another use-case is running sam build via CodeBuild with-in a CodePipeline. ie) when using the cdk [PythonFunction](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-python-readme.html) packaging feature it builds via this image under the covers. CodeBuild can be configured with a caching which should help but ideally this image should come from ECR where there are no rate limits applied.

**Comment by juluriaj** [comment]
> @ryosan-470 Thanks for the issue. We are still looking into ECR Public as an option.
> 
> Side note: Why are you running `sam local invoke` in CI? I would suggest running tests in CI on Lambda directly. There are differences between how docker behaves and AWS Lambda behaves. This could give you a false sense of things working. One example is multi-threading in python works locally but not in Lambda (due to the some directories being available in docker but not in Lambda itself). The `sam local` suite was written to support testing locally for quick debug cycles, not really within CI.

Hi @jfuss - IHAC who is looking to deploy lambda with containers to public ECR repo. So having the ability to push images to public ECR will definitely come a long way for my customer. Could you please provide any ETA when would this feature be available?

**Comment by jfuss** [comment]
@juluriaj This is not for pushing any image to Public Ecr but instead having SAM CLI pull emulation images we use from Public ECR (meaning we need those images in Public ECR). 

SAM CLI pushes images to ECR to support Lambda Images. Lambda only supports ECR and not sure if Lambda supports Public ECR for that. Since Public ECR is backed by ECR, this is already supported (in terms of pushing) but likely only for the ECR repo and not the Public ECR url. You can always try, seems like something easily to test.

**Comment by juluriaj** [comment]
> @juluriaj This is not for pushing any image to Public Ecr but instead having SAM CLI pull emulation images we use from Public ECR (meaning we need those images in Public ECR).
> 
> SAM CLI pushes images to ECR to support Lambda Images. Lambda only supports ECR and not sure if Lambda supports Public ECR for that. Since Public ECR is backed by ECR, this is already supported (in terms of pushing) but likely only for the ECR repo and not the Public ECR url. You can always try, seems like something easily to test.

@jfuss I've passed public ECR repo URL for image-repository argument. 

"Error: Invalid Image Repository ECR URI: public.ecr.aws/xxxxx/xxxxx"

Basically I'm having the same issue as others above.

**Comment by jfuss** [comment]
Emulation images are on [Public ECR](https://gallery.ecr.aws/sam). We have updated where SAM CLI pulls from and will be included in our next release.

Updating labels.

**Comment by xazhao** [comment]
It was released on 1.28.0. Closing this issue

**Comment by ryosan-470** [comment]
Oh! Thanks a lot!!
