### ISSUE TITLE
Docker 3.0.0 on Mac just hangs when running: sam build --use-container

### ISSUE THREAD

**Issue by aaronlelevier** [aws/aws-sam-cli#2471]
**Description:**

I updated Docker on Mac Catalina OS 10.15.7 and now when running `$sam build --use-container` SAM just hangs.

**Steps to reproduce the issue:**
1. Upgrade Docker Desktop on Mac to 3.0.0
2. Run `$ sam build --use-container`

**Observed result:**

Before there were dots being output for progress fetching the container. Now there's no dots and it hangs for at least 1 hour. I let it sit that long, then cancelled the command.

Here's a screenshot of the output when it hangs:

```
$ sam build --use-container

Starting Build inside a container
Building codeuri: lambdas/ runtime: python3.8 metadata: {} functions: ['my functions']

Fetching amazon/aws-sam-cli-build-image-python3.8 Docker container image......
Mounting /my/path/to/lambdas as /tmp/samcli/source:ro,delegated inside runtime container
```

**Expected result:**

`$ sam build --use-container` should work.

**References:**

Screenshot of Docker versions:

<img width="754" alt="Screen Shot 2020-12-10 at 12 23 24 PM" src="https://user-images.githubusercontent.com/5514112/101825675-c958ec00-3ae2-11eb-9611-fd5362e5ec07.png">

**Comment by mgrandis** [comment]
@aaronlelevier What output do you get when you add `--debug` to your command?
Running the same OS and CLI version here with a simple hello-world project with no issue.

**Comment by tfield** [comment]
I was seeing the same issue actually.  I ran the --debug flag and found that it was hanging while mounting my source directory.  It turns out that because I'm a mac user, and docker shared disk performance is abysmal on a mac, I had greatly restricted which directories are provided as shareable resources to Docker, in order to speed up container boot times.  As soon as I added my project root to docker's list of shared directories, the build ended up succeeding.  I did not get so granular as to expose my sources and the .sam-build folders separately. Performance is tolerable with my whole project folder being shareable.

**Comment by hughesjj** [comment]
Is there a way to change where `sam-cli` decides to mount to image to?  If so, is this a general docker feature I'm missing?

Sorry, new to the whole docker game.  To my understanding, sam-cli invokes docker on our behalf, and I can't find the relevant config when poking around `~/.aws-sam` or similar.

**Comment by trkohler** [comment]
any updates / siggestions on the problem?

**Comment by crwgregory** [comment]
After reading @tfield response, I edited my docker volume settings, initially I was mounting the entire `/User` directory. I removed that and added a mount to `/Users/myuser/dev` where I store all my dev work. That seemed to solve the issue for me.
