### ISSUE TITLE
requests.post auth in python sam lambda function failing

### ISSUE THREAD

**Issue by nealonhager** [aws/aws-sam-cli#2527]
### Description:
I'm trying to call an API in my python lambda function using the requests.post method, but it's failing. Outside of a lambda function, i.e. in a standalone python file, the requests goes through fine. Errors on sam local start-api and when deployed.

### Steps to reproduce:
```job_params = {'q':'test'}
headers = {"Content-Type": "application/json"}
response = requests.post("https://api.serpmaster.com/cb", headers=headers, json=job_params, auth=("xxx","xxx"))
```
sam build -t template.yaml
sam local start-api
invoke endpoint

### Observed result:
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'errorMessage', 'stackTrace'} in {'errorMessage': "HTTPSConnectionPool(host='api.serpmaster.com', port=443): Max retries exceeded with url: /cb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f0f0729d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))", 'errorType': 'ConnectionError', 'stackTrace': ['  File "/var/task/submit.py", line 65, in lambda_handler\n    auth=("XXX", "XXX")\n', '  File "/var/task/requests/api.py", line 119, in post\n    return request(\'post\', url, data=data, json=json, **kwargs)\n', '  File "/var/task/requests/api.py", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/var/task/requests/sessions.py", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/var/task/requests/sessions.py", line 655, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/var/task/requests/adapters.py", line 516, in send\n    raise ConnectionError(e, request=request)\n']}
2021-01-11 16:43:29 127.0.0.1 - - [11/Jan/2021 16:43:29] "POST /serp/submit/ HTTP/1.1" 502 -

### Expected result:
Expecting the request to go through.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: 1.15.0

**Comment by spirulence** [comment]
This could be a few things, depending on your local and deployed environments.

In your local, `sam local start-api` uses Docker and connects to the default bridge network unless you specify otherwise. Verify that you're able to connect to the internet from inside another running Docker container - in a server environment, this might be disabled for reasons that have nothing to do with SAM.

In your deployed environment, if you're using a VPC, check that outbound traffic is allowed. https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-networking.html

Your specific requests error has to do with domain resolution - if it turns out that your DNS settings are messed up, that could do this too. You can use a different DNS server, say 8.8.8.8 from Google, if needed.
