### ISSUE TITLE
[sam build/Feature] Turn off use of temp directory, allow to build in current folder

### ISSUE THREAD

**Issue by mribichich** [aws/aws-sam-cli#2655]
Have a flag to turn off the use of the **temp** directory when building. Basically the idea is to be able to use the **current src** path.

The temp directory doesnt work for situations like nodejs monorepos or common dependencies between projects.

Since once on folder is copied to this temp folder, it will loose all context.

So, ideally it would be to run the build in the same src folder.

For example, for people using **webpack**, coping everything to a **temp** dir, **installing**, etc, is a waste of time.

## My case:

We have a **nodejs monorepo** project with 20 lambdas. obviously we cant use common dependencies just like that, because of this **temp** dir. We also use **webpack**, so doing all of that is a waste of time.

we dont need **sam build** to **copy** and **install** for us.

one normally would run `yarn` or `npm install` on its own at the beginning.

And then we need a way to tell **sam build** what to copy to the artifacts dir. Using **gitignore** or **npmignore** is not appropriately here.

It would be awesome to have a **samconfig** that we could say what to **include** or **exclude**, maybe as a way of overriding defaults.

thanks

this feature would fix issues like these and probably others:

#2064
#2077

**Comment by pwinnski** [comment]
I think this might also solve some issues with sam and multi-module maven projects.

**Comment by spiceddest** [comment]
I just figured out that it's using a temp folder, and it also copies all the node_modules folder for each (!) function.
I have 30 functions in my project, so this really slows down the build step.

**Comment by ssenchenko** [comment]
We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, and we also try to take in popular feature requests based on 👍🏽 from the community. You can check the roadmap to see if your proposal has been prioritized for implementation.

**Comment by salvianreynaldi** [comment]
hope this feature is added soon 😄 

Here are my reasons:
1. To build a linux/arm64 GraalVM native-image binary with Quarkus + Gradle on MacBook Pro with Apple Silicon, I need to use a container (from quarkus side, not SAM). However, Rancher Desktop (since Docker Desktop is now not free to use) [doesn't mount the SAM temp directory by default](https://docs.rancherdesktop.io/faq/#q-does-file-sharing-work-similarly-to-docker-desktop-do-i-have-to-do-any-additional-configuration-to-mount-volumes-to-vms).
2. I usually include gradle dependency lock files, which are generated during gradle builds, to the version control. Since sam builds in the temp directory, I couldn't now which dependency versions are used during the build as there are no relevant lock files.

**Comment by nweajoseph** [comment]
without this SAM is almost unusable in node lambdas

**Comment by ceberz** [comment]
Our SAM project uses Typescript, and while the custom build feature has made Typescript compilation possible, having the option for an in-place build rather than copying would alleviate several pain points for us:

 - The time to copy the root directory can be pretty long if your project uses a traditional node_modules directory
 - Any local dependencies that exist _above_ the directory where the Makefile lives become a problem

**Comment by torresxb1** [comment]
Closing so that we can track in the above issue (`Feature request: Build in source`). There's multiple open issues relating to similar problems, so we want to have a central place to track.
