### ISSUE TITLE
Bottle for M1 Mac

### ISSUE THREAD

**Issue by andymac4182** [aws/aws-sam-cli#2673]
### Describe your idea/feature/enhancement

It would be great if there was a native M1 Mac bottle for homebrew.

**Comment by CoshUS** [comment]
Thanks for the feature request! We have a [roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) here, but we also try to take in popular feature requests based on 👍🏽 from the community. We will be adding this to our intake for prioritization.

**Comment by qingchm** [comment]
@andymac4182 Posting some updates on this issue! I think this issue is now addressed since our 1.66.0 release, https://github.com/aws/aws-sam-cli/releases/tag/v1.66.0, where we started publishing native PKG installers for ARM. To install using the PKG installer, please follow the installation guide on here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html. Hope that this native M1 installer brings excitement and convenience to you! If the preferred installation method is still homebrew instead of the PKG that we provide, please re-open this issue for us to track. We do have plans to create brew bottles with how new installers though, which would mean that homebrew bottle for ARM will also be available when that gets implemented.
