### ISSUE TITLE
Cant use MethodSettings in AWS::Serverless::Api

### ISSUE THREAD

**Issue by AllanOricil** [aws/aws-sam-cli#2746]
### Description:

Im trying to set ThrottlingBurstLimit to my api using the MethodSettings property but it is not working.

![image](https://user-images.githubusercontent.com/55927613/111890075-24518780-89de-11eb-8814-3111e77516f1.png)

I tried everything possible as it is saying here https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/
and here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html and nothing worked

### Steps to reproduce:
Try to use MethodSettings for all your APIs in a Stage using `- /` or `- "/" ` or `- /* ` or `- "/*"` and verify that none of these entries is accepted.

![image](https://user-images.githubusercontent.com/55927613/111890120-89a57880-89de-11eb-9412-4f96fe4c4003.png)

### Observed result:
Method setting for every api route in a stage is not working.

### Expected result:
Method setting for "/" should work.

These are the props I want to configure

![image](https://user-images.githubusercontent.com/55927613/111890410-fe79b200-89e0-11eb-8cda-3b03324794cb.png)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20
2. `sam --version`:  SAM CLI, version 1.8.0
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by AllanOricil** [comment]
Could anybody ramp up me to contribute to this project? I would like to fix this issue

**Comment by jfuss** [comment]
Moving to SAM because this relates to the Spec instead of the CLI. 

This is supported today but your template/definition is incorrect. You want something like:

```
...
  MethodSettings:
    HttpMethod: '/*'
    ThrottlingBurstLimit: 
    .....
```

MethodSettings is not a list it is a dictionary. Here is the SAM docs (which links out to the CFN docs on what the dictionary keys/values are accepted: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-methodsettings

Closing as this is not a SAM issue but an invalid definition. SAM just passes these values through to CFN, so that is why it fails during the deployment.
