### ISSUE TITLE
Build with environment variables passed to the build container from a file did not work

### ISSUE THREAD

**Issue by zcmgyu** [aws/aws-sam-cli#2758]
### Description:

As this the [AWS Document](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
) tutorial, I built a SAM project with an environment variable file and then deploy it to CloudFormation, the environment variable I set in the JSON file did not overwrite.

### Steps to reproduce:

**Build and deploy:**

> sam build --use-container --container-env-var-file env.json
> sam deploy --guided

**template.yaml**
```

Globals:
  Function:
    Environment:
       Variables:
          TABLE_NAME: OVERWRITE_BY_ENV_JSON

```

**env.json**
```
{
  "Parameters": {
    "TABLE_NAME": "HelloWorld"
  }
}

```

### Observed result:

But when I tried to get that TABLE_NAME key from `process.env`, it gives me `OVERWRITE_BY_ENV_JSON` value.
It worked perfectly when used on local.

### Expected result:

I can get TABLE_NAME is HelloWorld

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur
2. `sam --version`: SAM CLI, version 1.21.1
3. AWS region: Tokyo

`Add --debug flag to command you are running`

**Comment by qingchm** [comment]
Hey there I think there is some misunderstanding on what this option does! This option is only supposed to pass the env var to the build container, so that the build container can be set up the way you want it. However, the lifespan of this env var only lasts in the build process. It will not override any values in your template, and nor will it affect any behaviours on the cfn side. Thanks for bringing this up tho!
