### ISSUE TITLE
Request for Comment: Automatically Create ECR Repos with Companion Stacks

### ISSUE THREAD

**Issue by CoshUS** [aws/aws-sam-cli#2856]
## Problem:
Currently with `sam deploy` for image based functions, ECR repos must be created and specified before executing the deployment.
Issues: https://github.com/aws/aws-sam-cli/issues/2447#issuecomment-758337322 and https://github.com/aws/aws-sam-cli/issues/2672
## Solution:
We proposed solving this issue by automatically creating ECR repos through prompts in guided deployment or `--resolve-image-repos` similar to the current `--resolve-s3` option. For each deployed stack, a companion stack will also be created and ECR repos will reside in this companion stack to avoid inconsistency between local template and remote stack.
PRs: https://github.com/aws/aws-sam-cli/pull/2675 and https://github.com/aws/aws-sam-cli/pull/2815.
## Concerns:
With this implementation, the companion stacks will be left behind after the deployed stack is deleted. Although unreferenced repos will be cleaned up upon each redeployments, a deletion of the deployed stack either through console or other means will not affect the associating companion stack. A manual deletion for the companion stack and ECR repos will be required afterwards.
## Feedback
We would like to hear community feedback and thoughts on the current companion stack behavior of having lingering resources after the deletion of the original stack.

**Comment by solarmosaic-kflorence** [comment]
Honestly I have abandoned using SAM for anything except management of the function itself. I have found it easier to manage the rest in Terraform (granted, we already have a lot of our other infrastructure in Terraform). One sticking point was that I needed to have access to the policy for the function role ARN prior to executing SAM so I could properly test permissions in the CI/CD pipeline. So it was easier for me to manage that in Terraform and pass in the role ARN rather than having SAM manage it. Which is also the case currently for ECR.

**Comment by metaskills** [comment]
Thanks a few thoughts. First, I stand my previous comments here in 2447 but I will add that I do not use guided in any of the tooling I do both in open source or internal to Custom Ink.

* https://github.com/aws/aws-sam-cli/issues/2447#issuecomment-739045473
* https://github.com/aws/aws-sam-cli/issues/2447#issuecomment-751415672

Second, TIL I learn about `--resolve-s3`. I had to dig in issues and comments here since it is not in the official SAM CLI docs that I could tell. I love the idea of it and if I understand it correctly then I'd like to use this.

Following up from that, if `--resolve-image-repos` works as I expected it then I should be able to the following?

1. Remove these few lines https://github.com/customink/lamby-cookiecutter/blob/master/lambify/bin/_deploy#L6-L8
2. I add `--resolve-s3=true` here https://github.com/customink/lamby-cookiecutter/blob/master/lambify/bin/_deploy#L22 after the `--s3-bucket` line.
3. I can add `--resolve-image-repos=true` after this line https://github.com/customink/lamby-cookiecutter/blob/master/lambify/bin/_deploy#L21 in my `sam package` command.

Does all that sound right? And if so, both the S3 bucket and ECR repo will be created for me?

**Comment by CoshUS** [comment]
@solarmosaic-kflorence @metaskills 
Thank you for the feedback!

@metaskills 
`--resolve-image-repos` creates a 1:1 mapping between deployed stack and its companion stack, which means it does not work for the `sam package` command currently. `--resolve-s3` behaves differently as it creates a companion stack per account per region instead of per stack.

In the context of your `_deploy` bash script, deploy can be directly used as it calls `sam package` automatically. 
Updated script with `--resolve-image-repos` and `--resolve-s3`:
```
#!/usr/bin/env bash
set -e

./bin/_build

sam build \
  --parameter-overrides \
    RailsEnv="${RAILS_ENV}"

echo "== SAM deploy..."
sam deploy \
  --region "$AWS_DEFAULT_REGION" \
  --template-file ./.aws-sam/build/template.yaml \
  --stack-name "{% include "_cctmp/dash_name.txt" %}-${RAILS_ENV}" \
  --resolve-image-repos \
  --resolve-s3 \
  --capabilities "CAPABILITY_IAM" \
  --parameter-overrides \
    RailsEnv="${RAILS_ENV}"
```

**Comment by solarmosaic-kflorence** [comment]
By the way, I should mention that I still need to deploy with `--image-repository <full ECR url>`, even though the packaged template already includes the full ECR url. Would be nice to not have to do that.

**Comment by Rabadash8820** [comment]
Personally, I would rather the relationship between Lambda Function and ECR Repository be set up in _my_ CloudFormation template, alongside my existing resource definitions, rather than in some new CLI parameter or auto-generated stack. Admittedly, this would probably require changes to CloudFormation itself, rather than SAM. But I could see something like using the `DependsOn` attribute of a `AWS::Serverless::Function` resource to specify the logical ID of an `AWS::ECR::Repository` resource in the same template. CF would know to create the Repository first, then upload the image, _then_ create the Lambda function using that image.

**Comment by metaskills** [comment]
Kind of agree. I'm torn between 1st user experience and experienced usage. When in conflict, I always defer to 1st user experience.

**Comment by Rabadash8820** [comment]
Bot comment acknowledged... but also why has this issue been closed? I know this issue is just an RFC, but what exactly has been resolved? It would be nice to get some comments on where SAM's developers will be going from here, otherwise I feel like our comments have just been lost to the void.

**Comment by CoshUS** [comment]
@Rabadash8820 
Thank you for your feedback. This issue is intended to specifically gather concerns over auto created repo companion stack. Because of that, I have closed this issue in favor of the original [PR](https://github.com/aws/aws-sam-cli/pull/2815) and [issue](https://github.com/aws/aws-sam-cli/issues/2447#issuecomment-758337322).


However, this does not mean comments in this thread will be lost. 
The bug for specifying `--image-repository` even when CodeURIs are pointing to ECR repos will be handled outside of this scope.
And your proposal for using ECR repos in the same template is also tracked in https://github.com/aws/aws-sam-cli/issues/2672. Although, it's currently blocked by limitations of CFN, we will revisit that solution if CFN changes their behavior.

**Comment by Rabadash8820** [comment]
@CoshUS I see, thanks for the clarification. #2672 is exactly what I was hoping for!
