### ISSUE TITLE
CodeBuild: sam package computes a different MD5 hash for unchanged lambda source code

### ISSUE THREAD

**Issue by serjkazhura** [aws/aws-sam-cli#2872]
### Description:

Setup i am having:
- a lambda function written in `node.js`
- sam template for that lambda
- `buildspec` that is running `sam build` and  `sam package`
- everything is deployed via `CodePipeline` and is using `CodeBuild`
- code is deployed to `github`
- `sam package` that is running on the `CodeBuild` instance is computing a new `MD5` hash for the lambda source code in spite of lambda function being changed or not
- i believe it has to do with the fact that `CodeBuild` environment is ephemeral, and the way we are calculating `md5` hash [here](https://github.com/aws/aws-sam-cli/blob/686369638c9d23f2cf9d5821177bce716dd8893f/samcli/lib/package/utils.py).

Code snippet:
```python
@contextmanager
def zip_folder(folder_path):
    """
    Zip the entire folder and return a file to the zip. Use this inside
    a "with" statement to cleanup the zipfile after it is used.
    Parameters
    ----------
    folder_path : str
        The path of the folder to zip
    Yields
    ------
    zipfile_name : str
        Name of the zipfile
    md5hash : str
        The md5 hash of the directory
    """
    md5hash = dir_checksum(folder_path, followlinks=True)
    filename = os.path.join(tempfile.gettempdir(), "data-" + md5hash)

    zipfile_name = make_zip(filename, folder_path)
    try:
        yield zipfile_name, md5hash
    finally:
        if os.path.exists(zipfile_name):
            os.remove(zipfile_name)
```

### Steps to reproduce:

- Create a simple lambda with sam
- create a `buildspec` that will run `sam build` + `sam package`
- Create `CodePipeline` with `CodeBuild` step
- Go to `CodePipeline` and run `Release Change` multiple time (essentially you are building the same revision)

### Observed result:

- lambda is being redeployed each time you run `release change` in code pipeline

### Expected result:

- this should not result in lambda being redeployed every time you run `release change`, since there were no code changes made

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
I will create a sample repo with the code shortly

**Comment by aahung** [comment]
What is the SAM CLI version? We fixed an issue #2110 where SAM CLI uses the absolute path to calculate the md5, which may result in different md5.

**Comment by serjkazhura** [comment]
here is the [repo](https://github.com/serjkazhura/sam-lambda-cicd) that you can use to reproduce the issue. i outlined the steps in the `readme`.
i am using `pip3 install --upgrade aws-sam-cli` so, in theory, we should always have the latest version of `sam cli`

**Comment by Karthi96** [comment]
@serjkazhura @aahung  I found some solution for this and also I don't think anything wrong with aws-cli for this issue. 

As we know the md5 checksum varies across the system and this is the reason why cloud formation is redeploying the lambda always though you haven't changed the lambda code from the code pipeline. The reason is, build stage is connected with the source stage, and the build stage always clones the repo and it thinks as a fresh new copy, so it will deploy all. But if you have a .git folder then the build will pull only the latest code. 

There is an option where you can set the cache of the build system to retain across the builds. If you set these options, then you won't see the redeploying the lambda. 

![Screenshot from 2021-05-31 02-07-54](https://user-images.githubusercontent.com/17947667/120119431-44a77a80-c1b5-11eb-9890-c60646e5f9b4.png)

### How to set caching across builds

1. Go to build project and see the build details
2. Navigate to Artifacts and Click on Edit
3. Click on additional configuration and select the cache type to `local`
4. Select all the checkboxes especially `source cache` if needed other checkboxes which will make deployment faster 


I have personally tested this and it is working fine. Feel free to reach out to me if you need any assistance. 


Thanks, 
Karthikeyan B

**Comment by mndeveci** [comment]
Hi @serjkazhura ,

I tried to re-produce the issue you mentioned, by cloning the application that you linked and then running the build & deploy. And then I ran same sequence couple of times, but all the time, deploy is skipped because files are the same ones that is been deployed previously. I also tried to move the project folder to somewhere else and re-run the same sequence again, but result was the same, deploy was skipped because content is the same (`File with same data is already exists at`). I also re-cloned the app into another folder and re-run everything again but result was the same.

As @aahung  mentioned there was an earlier issue which was causing md5 calculations to be different when running in different folders, but this issue have already been fixed.

Can you verify that you still experience the issue? And maybe more detailed steps to reproduce?

Thanks!

**Comment by Karthi96** [comment]
@mndeveci  How are you deploying the stack in local env or via code pipeline? If you deploy via local then it works well but when you use code pipeline with code build and code deploy then the complete stack is redeploying without any modification. so the problem is md5 varies when deploying stack from the new environment.

**Comment by vijay2kr** [comment]
@mndeveci - The issue can be reproduced as follows in Code Pipeline:
1. Source stage - Github repo
2. Build stage:
sam build
sam package --output-template-file packaged.yaml --s3-bucket <S3 bucket>
3. Deploy stage:
CloudFormationCreateUpdateStackAction

**Comment by rakwal** [comment]
@serjkazhura This is still an issue.Even when no change is done , sam build still does the entire build .This issue is impacting as this is increasing the build and deployment time.I am using sam build in codebuild step of codepipeline.

**Comment by suroh1994** [comment]
I've encountered the same issue but with an application written in Golang. Running `sam build` and `sam package` locally exhibits the expected behaviour of not reuploading the unchanged binaries. However, when I'm using CodeBuild to perform these two actions, it will result in every binary being reuploaded, no matter whether anything changed or not.

**Comment by suroh1994** [comment]
To verify it's not due to an old installation of the SAM CLI, I added the lines to install the latest version (1.31.0) and the problem persists.

**Comment by j-fraga** [comment]
I confirm the same issue with SAM CLI v1.33.0 (x86_64).

Steps to reproduce:

1. `sam build --use-container`
2. `cd .aws-sam/build  &&  tar cvf <FUNCTIONNAME>`
3. `md5sum <FUNCTIONNAME>.tar`
4. `sam build --use-container`
5. `cd .aws-sam/build  &&  tar cvf <FUNCTIONNAME>`
6. `md5sum <FUNCTIONNAME>.tar`

The output of the first `md5sum` is different from the output of the second.

**Comment by wchengru** [comment]
I have reproduced and investigated this issue. I think the root cause is the codebuild directory includes a random filename.
Because SAM CLI uses the absolute path to calculate the md5, the working directory name will change the calculated hash.
To resolve this, you can simply move the working dir into a location with fixed name. For example, move it under `/tmp`.

**Comment by serjkazhura** [comment]
I can confirm that the `tmp` directory works. This is a workaround though, so everyone should be aware of it to take advantage of it. I will work with `SAM cli` team on better documenting it.
This is the `buildspec` I was using to confirm:
```json!

install: {
  'runtime-versions': {
    nodejs: 12,
    python: 3.8
  }
},
'pre_build': {
  commands: [
    'pip3 install --upgrade aws-sam-cli',
    'mkdir /tmp/build',
    'mv services /tmp/build/',
    'cd /tmp/build',
    'cd services/user-service/users-lambda',
    'npm install'
  ]
},
build: {
  commands: [
    'cd ..',
    'sam build --debug',
    'sam package --s3-bucket $PACKAGE_BUCKET --s3-prefix \'user-service\' --output-template-file packaged.yaml --debug',
    'aws s3 cp packaged.yaml s3://$PACKAGE_BUCKET/user-service/'
  ]
}
```

**Comment by eduardhasanaj** [comment]
@serjkazhura I am facing the same problem but on mac os. After I deploy I build again and deploy and all lambas are updates despite of no changes in code. I am using typescrip template.
