### ISSUE TITLE
Connecting vs.code to my container for IntelliSense

### ISSUE THREAD

**Issue by jacobSingh** [aws/aws-sam-cli#2954]
### Describe your idea/feature/enhancement

vs.code has support for docker.  It let's you connect your Dev environment to a running container.  This is useful because it's nice to keep all your dependencies clean inside the container and not cluttering your system and using virtualenvs and all.

But with sam, I can't seem to do this... if I run SAM Local start-api I thought it would show, but it doesn't...  More of a support request probably, but I don't get how to do this.

### Proposal

Well, if it isn't there already, probably just a way to load my image and keep it running while I'm developing.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

**Comment by mndeveci** [comment]
Hi @jacobSingh ,

Could you elaborate a little bit more on the request? You have your project inside Docker container, and you want to access the source code so that intellisense on the VSCode will work? Or you have the project inside docker container and you want to run `sam local invoke` to test your lambda locally?

**Comment by sriram-mv** [comment]
Closing this issue, SAM has support through vscode through AWS Toolkits: https://aws.amazon.com/visualstudiocode/ this maybe what you are looking for.

If this is not, what you were after please re-open an issue after answering @mndeveci's questions.
