### ISSUE TITLE
New version of major python libraries can't be accessed for weeks

### ISSUE THREAD

**Issue by idwise-team** [aws/aws-sam-cli#3125]
### Description:
It happened to us many times, we try to use a newly issued version of a certain well-known library in Python (the new version is available on Conda and PIP), but we try to use it via AWS SAM CLI, the build fails to say something like this:
Error: PythonPipBuilder:ResolveDependencies - {xxxx==x.y.z(wheel)}

We go back to a previous version, it all works fine.

Is there some sort of AWS-specific package repo that is late to update libraries? and how can we ensure our app uses the latest and greatest libraries (especially if a certain library has a major bug or security issue)?

### Steps to reproduce:
The last example is pymongo:

Error: PythonPipBuilder:ResolveDependencies - {pymongo==3.12.0(wheel)}

The above version of pymongo was published to pip more than two weeks ago!

But this is not the only one, we had it with a handful of major libraries, 

### Observed result:
Error: PythonPipBuilder:ResolveDependencies - {pymongo==3.12.0(wheel)}

### Expected result:
For the library to be usable on day one of launching a new version.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
My development workstation is .
1. OS: Windows Server
2. `sam --version`:  1.23.0
3. AWS region: N/A

**Comment by sriram-mv** [comment]
SAM CLI uses aws lambda builders behind the scenes to build dependencies, its likely trying to pull wheels that match a certain contract within the aws lambda builders python pip builder. I'll look into reproducing this.

**Comment by mndeveci** [comment]
Hi @idwise-team,

Thanks for raising this issue. As per previous comment, SAM CLI uses certain `pip` commands to pull dependencies from pypi, we are not using any other repository for this.

And any new library version should be available as soon as it is been updated in pypi. You might started to see these failures, if certain library;
- Drops supports for the python version that you are using
- Introduces a native dependency which can only be built in a linux environment

You need to upgrade python version for the first one. And for the second one, I would suggest to use `sam build --use-container` so that dependencies will be built in a linux environment.

Please let us know if you still experience this issue.

Thanks!

**Comment by moelasmar** [comment]
Thanks @idwise-team for raising the issue. We will close this issue as it is inactive for more than two weeks. If you still have the same issue, or any other issues, please open a new issue.
