### ISSUE TITLE
Error: Template file not found

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli#3138]
### Description:
Error: Template file not found at /home/runner/work/sam-pipeline-test/sam-pipeline-test/template.yaml

### Steps to reproduce:
Follow https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/

### Observed result:
```
Error: Template file not found at /home/runner/work/sam-pipeline-test/sam-pipeline-test/template.yaml
Error: Process completed with exit code 1.
```
https://github.com/kaihendry/sam-pipeline-test/runs/3217491951

### Expected result:
Successful build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

OS: Linux
sam --version: SAM CLI, version 1.27.2
AWS region: ap-southeast-1

**Comment by jfuss** [comment]
@kaihendry By looking at app, it seems like you want to be running `sam pipeline init` inside `sam-app` (or the `sam init`'ed directory) not the root. Stated a little more broadly, you want to run `sam pipeline init` in the same directory as your `template.yaml`. 

Looking at the blog though, I don't see a "change directory" note anywhere. So I totally see how you ended up running in the a different directory. 

Let me validate with the team. @c2tarun Might know off hand.

**Comment by jfuss** [comment]
Had a chat with some team members. `sam pipeline init` should be run within the `sam-app` directory. Your repo will need some updates though:

Everything in the `sam-app` should be in the root directory. `sam init` creates a new directory for your application, which is meant to be the root instead of being embedded into another project. You can embed it, just makes the commands and configuration much more work. So wouldn't recommend that unless you really need to.

**Comment by jfuss** [comment]
[The blog](https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/) was update. This should be resolved now. 

Going to leave open for a little while in case you have follow up questions @kaihendry.
