### ISSUE TITLE
SAM CLI not executing Node.js lambda on Apple M1

### ISSUE THREAD

**Issue by verminator23** [aws/aws-sam-cli#3142]
### Description:

The SAM CLI is not successfully calling my Node v12 lambda functions. It gets stuck on the mounting step:
```
yarn run v1.22.10
$ sam local invoke -t ../template.yml UpdatePostPreviewFunctionProd -e events/events.json
Invoking index.handler (nodejs12.x)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs12.x:rapid-1.27.2.

Mounting /Users/vernonjohnson/Desktop/yup/yup-monorepo/lambdas/update-post-preview as /var/task:ro,delegated inside runtime container
```

### Steps to reproduce:

Run  ```sam local invoke -t ../template.yml [function name] -e events/events.json```.

### Observed result:

```
yarn run v1.22.10
$ sam local invoke -t ../template.yml UpdatePostPreviewFunctionProd -e events/events.json
Invoking index.handler (nodejs12.x)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs12.x:rapid-1.27.2.

Mounting /Users/vernonjohnson/Desktop/yup/yup-monorepo/lambdas/update-post-preview as /var/task:ro,delegated inside runtime container
```

### Expected result:

The cli to execute the lambda function.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Big Sur v11.3
2. `sam --version`: SAM CLI, version 1.27.2
3. AWS region: us-east-1
4. `docker version`: Docker version 20.10.7, build f0df350

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@verminator23 So my understanding is M1 should work. Stuck on mounting (at least in Windows) has been due to shared drives. It seems like an image was built so can you check the following:

1) Do you have the shared settings for the directory you are in on? Can check in the docker desktop app.
2) Can you run a docker image outside SAM CLI?
3) Assuming the docker version you have supports M1?

These are the typically things I have seen. I will reach out to some team members who are on M1 (I am not), to do some basic checking.

**Comment by aahung** [comment]
I cannot reproduce it with

- SAM CLI 1.27.2
- docker desktop 3.5.2 (66501)
- docker 20.10.7 (f0df350)
- a nodejs 12 SAM function

**Comment by aahung** [comment]
@verminator23 can you run `local invoke` with `--debug` flag to see whether we can get more information?

**Comment by xazhao** [comment]
@verminator23 Do you still have this issue? It seems @aahung has M1 Mac and SAM CLI works fine on his Mac.

**Comment by xazhao** [comment]
Closing this issue now. Please feel free to reopen this issue if you have any further questions.
