### ISSUE TITLE
Billing Duration reported in 100ms intervals

### ISSUE THREAD

**Issue by danPudwellUK** [aws/aws-sam-cli#3144]
### Description:
When using `sam local start-api` the billing duration is reported in 100ms intervals

### Steps to reproduce:
I used the Hello World quick start template
Run `sam local start-api --port 8080`
Hit the function

### Observed result:
Duration: 255.59 ms     Billed Duration: 300 ms

### Expected result:
I would have expected billing duration to be 256ms

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
I ran it in Cloud9

I looked through the code and couldn't find anything in this repo relating to printing this out.  I'm assuming its pulling this in from somewhere else so maybe an old dependency?

**Comment by jfuss** [comment]
The "reporting" line in the output is done by RIE and fixed in this PR: https://github.com/aws/aws-lambda-runtime-interface-emulator/pull/7

We have a PR to pull in the new RIE binary: https://github.com/aws/aws-sam-cli/pull/3029 but there were some issues that we haven't fully diagnosed yet. Once that PR is merged and released, this will go away. 

As a note, this is purely output in the CLI. Lambda does the correct thing for billing.

Updating labels.

**Comment by jfuss** [comment]
Closed by accident.

**Comment by jfuss** [comment]
This was merged in https://github.com/aws/aws-sam-cli/pull/3216 and released already.

Closing
