### ISSUE TITLE
Nested stack makefiles are run but not deployed as expected

### ISSUE THREAD

**Issue by cwilliamsonslyp** [aws/aws-sam-cli#3196]
### Description:
This appears to be a similar issue to the closed ticket https://github.com/aws/aws-sam-cli/issues/1470
When using nested stacks with a AWS::Serverless::Function resource built by makefile, the makefile is run and .aws-sam shows the correct build output, but the entire folder specified by CodeUri is uploaded to lambda.

### Steps to reproduce:

1. Download the attached zip [nested-stack-bug.zip](https://github.com/aws/aws-sam-cli/files/7034781/nested-stack-bug.zip)
2. Populate the parameters in the deploy.sh script as required (s3-bucket, stack-name, etc)
3. Run the deploy.sh script

### Observed result:

There are no errors
.aws-sam/build shows the expected makefile result
![image](https://user-images.githubusercontent.com/64388493/130514573-f9f1aac0-b52d-4fab-b664-9fd40514ec9d.png)

The deployed lambda contains all code in the folder targeted by CodeUri
![image](https://user-images.githubusercontent.com/64388493/130515518-6b65601e-e881-4a79-ba42-ab8f162f3dd3.png)

### Expected result:
The deployed lambda should contain the same files as the `.aws-sam/build/IngesterStack/IngesterFunction` folder

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.5.2
2. `sam --version`: SAM CLI, version 1.24.1
3. AWS region: ap-southeast-2

Thanks in advance for your help

**Comment by jfuss** [comment]
@cwilliamsonslyp  In the `deploy.sh`, you are overriding the `-t` and pointing SAM CLI to the source template file: `sam deploy -t parent-template.yaml --stack-name $stack_name --s3-bucket $bucket_name --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND`. Instead, you should drop the `-t`: `sam deploy --stack-name $stack_name --s3-bucket $bucket_name --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND`. This will allow SAM CLI to pick up the the built templates instead of our "source" template.

**Comment by cwilliamsonslyp** [comment]
Thanks @jfuss. Funnily enough I read through the docs with fresh eyes this morning, saw that part of the documentation (facepalmed..) and came to update the ticket as resolved, but you beat me to it.

Thanks for the quick response 😃
