### ISSUE TITLE
sam-cli-beta-cdk tag points to wrong commit (?)

### ISSUE THREAD

**Issue by kini** [aws/aws-sam-cli#3289]
On [this GitHub release](https://github.com/aws/aws-sam-cli/releases/tag/sam-cli-beta-cdk) titled "[BETA] SAM CDK Support V3.0: Update SAM CLI version to 1.29.0", the git tag associated with the release is [`sam-cli-beta-cdk`](https://github.com/aws/aws-sam-cli/tree/sam-cli-beta-cdk), but that git tag points to commit 962ba9de0514c5815519bed0549d043650460bd5 from back in April. When I click [Source code (zip)](https://github.com/aws/aws-sam-cli/archive/refs/tags/sam-cli-beta-cdk.zip) on the release page, the zip file that gets downloaded does seem to contain old code from back in April, with `samcli/__init__.py` showing version 1.23.0.

Maybe the `sam-cli-beta-cdk` tag was supposed to point to commit 93e25160b2d3b740895203b44cac087e670dc2e1 (the current tip of branch `cdk-support` as of today, Sep 19 2021), instead? 93e25160b2d3b740895203b44cac087e670dc2e1 does actually look like a bump to 1.29.0.dev202108311500, which the description of the GitHub release does mention:

> ### What's new in Beta V3.0 release:
>
> * Update SAM CLI version to 1.29.0 (SAM CLI Version number: 1.29.0.dev202108311500)

**Comment by wchengru** [comment]
Hi @kini , thanks for the feedback. 
This release tag is not exactly pointing to the latest commit because we have to maintain stable download links in the SAM CLI [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-getting-started.html). For example, the download link https://github.com/aws/aws-sam-cli/releases/download/**sam-cli-beta-cdk**/AWS_SAM_CLI_64_PY3.msi. The tagged commit is updated but the only the artifacts are updated. This will make our downloads/installations maintainable.
The [commit](https://github.com/aws/aws-sam-cli/commit/93e25160b2d3b740895203b44cac087e670dc2e1) you mentioned should be the correct latest branch. I will update this in our release note.
If you want to check the latest release version and commit, please check the link in our brewbottle installation [config](https://github.com/aws/homebrew-tap/blob/master/bottle-configs/aws-sam-cli-beta-cdk.json)

**Comment by CoshUS** [comment]
Closing as the reasoning mentioned above.
