### ISSUE TITLE
Makefile go.x to use Graviton with provided.al2 runtime

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli#3338]
Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] is what I see with https://github.com/kaihendry/days

if I update `-o ${ARTIFACTS_DIR}/bootstrap`, I then get `Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint` which makes no sense as it's ARM aarch64.

### Description:

Upgrade my Makefile powered go application to use Arm

### Steps to reproduce:

2. git clone https://github.com/kaihendry/days.git
3. Deploy and see issues

### Observed result:

https://s.natalian.org/2021-10-05/debug.txt

### Expected result:
A smooth upgrade to **GOARCH=arm64**

```
2021/10/05/[$LATEST]0938a24bbc4948958ccc97d3872b0943 2021-10-05T11:33:21.353000 RequestId: 0d01fbf8-b09f-4a39-9507-5d37f84d792e Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint
(ins)[hendry@t14s tmp]$ unzip ~/Downloads/days-MainFunction-lFEDC4UA9M9E-1b0c72e9-0e61-4768-b865-aee880ada73d.zip
Archive:  /home/hendry/Downloads/days-MainFunction-lFEDC4UA9M9E-1b0c72e9-0e61-4768-b865-aee880ada73d.zip
  inflating: bootstrap
(ins)[hendry@t14s tmp]$ file bootstrap
bootstrap: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=rDCvRCoJfgoyY1iVDIZG/gr7EGgy4ZNt4oDN7goqG/uUcq5dYY09S60xmjxPqR/-H9Tw2smUe2o2wGiTkoQ, not stripped

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

2. `sam --version`: SAM CLI, version 1.33.0
3. AWS region: ap-southeast-1

**Comment by valerena** [comment]
Hi. I got confused with [the tweet](https://twitter.com/__steele/status/1443357130992455681) you linked in [your commit](https://github.com/kaihendry/days/commit/6b7fe7894fa252fc18d70df1d7abd7555fdeb47c). Unfortunately, Moving from a `go1.x` runtime to a `provided.al2` runtime is not as easy as just changing the `runtime` value.

Your `main` file will still be `main`, but to use a custom runtime, you need an **extra** `bootstrap` file, that won't be your function's handler directly, but it will be a script that will talk with Lambda's Runtime API, getting the incoming function events from that API and after than interacting with your handler. There's more information in [the public documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html).  

I imagine that the user that tweeted that you had to "use provided.al2 runtime" probably already has a `bootstrap` file for their function.

For Runtimes not supported by Lambda, there are existing bootstraps ([bash](https://www.proud2becloud.com/how-to-run-any-programming-language-on-aws-lambda-custom-runtimes/), [php](http://p.agnihotry.com/post/php_aws_lambda_runtime/), [perl](https://medium.com/@avijitsarkar123/aws-lambda-custom-runtime-really-works-how-i-developed-a-lambda-in-perl-9a481a7ab465)), but I'm not aware of a custom runtime to run Go functions, and that's what you would need to be able to "just" migrate to arm64 in Go even before it's supported natively by Lambda.

**Comment by kaihendry** [comment]
No, I'm unable get it to work on my simple project: https://github.com/kaihendry/days

**Comment by qingchm** [comment]
@kaihendry I think the problem here is that you tried to specify the runtime in the template to be provided.al2 but this is not supported. Go does not have a custom runtime supported by lambda. In order for a Go function to work the runtime value can only be go1.x like it is specified in your provided sample. The runtime value cannot be modified.

**Comment by kaihendry** [comment]
Thanks, I do think my repo https://github.com/kaihendry/days is pretty minimal. If you or the tooling can't make it work, then the *arm64* story is not very compelling, in fact, I'd say off putting.

Perhaps publish a working example (with your shell hack) and close this?

**Comment by valerena** [comment]
Hi again. I was investigating a bit more, and Go is indeed different than other languages in the sense that you **can** just use it directly as a boostrap file with `provided.al2` runtime because of the way that Go initializes and runs a function. 

Taking that into account, I checked with the Go example created through `sam init` and the change needed to use `provided.al2` and `arm64` was indeed very minimal (You can check the change needed [here](https://github.com/valerena/basic-go-arm64/commit/1d3b6dc075ff5a77241b2d35a2379b81ca223379#diff-f319befdac42f61120a64fe758334038ff330a2b8de22bce30ba7a1cd59549ee) and the rest of the code in that repository).

You have to consider that Go is still not officially supported for arm64 in Lambda, so you will have to wait until that's supported to have a real smooth transition, and for now everything is going to be kind of hacky.

Sorry for the confusion earlier, and unfortunately it's your code in particular the one that has a specific issue and it's not a general problem like I imagined before.

**Comment by wchengru** [comment]
Hi @kaihendry , with the change above, I can deploy the example stack and invoke the function. Can you please try it and see if it works in your project?

**Comment by kaihendry** [comment]
Still fails with *Task timed out after 3.00 seconds*

I'm absolutely puzzled how to proceed https://github.com/kaihendry/days/commit/56094c60f4de449f349e11acab3fab60d40865e6

**Comment by wchengru** [comment]
The line below in your function caused the timeout, for both `go1.x` and `provided.al2`:
`err = http.ListenAndServe(":"+os.Getenv("PORT"), nil)`
This line only appears in branch `if port == ""`. For this reason, `go1.x` didn't go through this line because the environment variable `_LAMBDA_SERVER_PORT` is implicitly defined. However, this is not defined in `provided.al2` case.
Looking the document of AWS Lambda environment variables, `_LAMBDA_SERVER_PORT` is not a reserved environment variable: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
To avoid this when migration your function to `provided.al2`, you can define `_LAMBDA_SERVER_PORT` by yourself.

**Comment by kaihendry** [comment]
Thank you for your help! I ended up using **AWS_LAMBDA_FUNCTION_NAME**. There isn't much giving it away that it's running on arm64, right? https://sarm.goserverless.sg/

	if _, ok := os.LookupEnv("AWS_LAMBDA_FUNCTION_NAME"); ok {
		log.Fatal(gateway.ListenAndServe("", routes()), nil)
	} else {
		log.Printf("Assuming local development")
		log.Fatal(http.ListenAndServe(fmt.Sprintf(":%s", os.Getenv("PORT")), routes()), nil)
	}
