### ISSUE TITLE
Parameter overrides is stripping double quotes

### ISSUE THREAD

**Issue by VaughanJ** [aws/aws-sam-cli#3508]
The following CLI call:
`sam deploy --template-file package.yml --stack-name codedeploylambda-test --capabilities CAPABILITY_IAM --no-progressbar --region us-west-2 --parameter-overrides Parameters="{"Databus__Exchange":"tel_bus_v1","Databus__Exchange1":"tel_bus_v2"}"`

Passes JSON to to the --parameter-overrides via Parameters.

However when the CLI displays the inputted values it's shows as follows:

`Parameter overrides          : {"Parameters": "{Databus__Exchange:tel_bus_v1,Databus__Exchange1:tel_bus_v2}"}`

![image](https://user-images.githubusercontent.com/3703414/144221027-ccd14d21-3ee0-430b-8188-438a1ef2a6f6.png)

Which is stripping the double quotes out of the JSON making it invalid. I have tried different methods to escape it, but nothing seems to be working. I have also tried to do the same via a samconfig.toml file. All without any luck.

And when the Parameters are created in the Lambda, they are also missing the double quotes.

**Comment by xazhao** [comment]
Hi Jon!

`--parameter-overrides` will accept a string encoded as key-value pairs instead of JSON. For example, `ParameterKey=ParameterValue InstanceType=t1.micro`.

These two docs have a good explanation of option `--parameter-overrides`:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/

Closing this issue now. Feel free to reopen it if you have any further questions.

**Comment by VaughanJ** [comment]
Thanks xazhao for the documentation links, but I think I have a valid use case, I have a Lambda that is expecting one of it's values to be a JSON object. We can look into refactoring our Lambdas to only use key value pairs, but I'd like to know if the sam cli --parameter-overrides can take JSON as the value via some escaping mechanism.

**Comment by VaughanJ** [comment]
Can this issue he reopened please?

**Comment by VaughanJ** [comment]
@xazhao can this be re-opened please?

**Comment by VaughanJ** [comment]
I believe this PR fixed the above issue:
https://github.com/aws/aws-sam-cli/pull/3226

**Comment by mieliespoor** [comment]
This looks to have been merged via #3533
