### ISSUE TITLE
Running AWS SAM local invoke inside Docker

### ISSUE THREAD

**Issue by adityagoel123** [aws/aws-sam-cli#3588]
Unfortunately, I can't install SAM-TOOLKIT (sam-cli) on my host computer MAC because of restrictions, but I have Docker installed.

Now, I work inside Docker flawlessly. I have started the docker-container (from base image of Linux Ubuntu) and have installed all necessary softwares inside the Container like "sudo", "JDK", "maven", "vim", "aws-cli", "sam-cli", etc.

I am perfectly able to run and execute "sam build" && "sam deploy" commands inside my docker-container, but when I try to execute the command like "sam local invoke HelloWorldFunction/ --event events/testEventWithOneParameter.json " I am getting below error :-

Error: Running AWS SAM projects locally requires Docker. Have you got it installed and running?

How do I now solve this problem of having Docker inside Docker ? Your early response shall be highly appreciated.

Sitting inside a Docker container, can I test out my Lambda functions ??

**Comment by qingchm** [comment]
@adityagoel123 Hey there to understand your issue here may I first ask which way you tried to install sam-cli failed with restriction issue? Are you not able to use brew to install like introduced here? https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

**Comment by jfuss** [comment]
Closing given no response.
