### ISSUE TITLE
SAM pipeline removed after deploy

### ISSUE THREAD

**Issue by CGarces** [aws/aws-sam-cli#3752]
### Description:

I'm using the hello world template with python 3.8 to test the "sam pipeline bootstrap" feature.

I'm executing
sam deploy -t codepipeline.yaml --stack-name sam-desarrollo --capabilities=CAPABILITY_IAM 

In order to deploy the pipeline. It fails in my case due the github connection.

After update GitHub connector and retry the pipeline, it start normally but in some point, the pipeline itself is deleted.

### Steps to reproduce:

`sam init`
select python 3.8 and hello world proyect.
`sam pipeline init --bootstrap` 
Select AWS Pipeline as CI/CD, github as git provider.
`sam deploy -t codepipeline.yaml --stack-name myStack --capabilities=CAPABILITY_IAM`

At this point the pipeline will fail. Update the pending conection for github.

Push the generated pipeline files to git, it will trigger the pipeline.

The pipeline start normally but at some point, is removed.

### Observed result:

Cloud trail show a DeletePipeline event.

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "xxxx:AWSCloudFormation",
        "arn": "arn:aws:sts::xxxx:assumed-role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-5524JO8QQ6S9/AWSCloudFormation",
        "accountId": "xxxx",
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2022-03-16T18:01:26Z",
    "eventSource": "codepipeline.amazonaws.com",
    "eventName": "DeletePipeline",
    "requestParameters": {
        "name": "MyStack-Pipeline-11AZSNLODS7NX"
    },
}

```

### Expected result:

Keep pipeline, I have no idea why is removed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

SAM CLI, version 1.40.0

`Add --debug flag to any SAM CLI commands you are running`

**Comment by dorlanpabon** [comment]
También tengo el mismo problema, en este caso estoy realizando la implementación con NODE 14.x, hago los mismos pasos que tú, y al final se elimina la canalización.

**Comment by CGarces** [comment]
I think that the "pending connection" for github is raising some rollback status on the cloudformation stack.
Maybe tweak the "CodeStarConnectionArn" on codepipeline.yaml solve the problem, but it should be just a workaround.

**Comment by dorlanpabon** [comment]
@CGarces Amigo, ¿has podido solucionar el inconveniente?, yo aun tengo problemas.
¿Sabes de algún tutorial que me puedas regalar para crear la canalización manualmente?

**Comment by dorlanpabon** [comment]
@CGarces , ya encontre el fallo, cuando envies el comando **sam deploy -t codepipeline.yaml --stack-name codepipeline-1 --capabilities=CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset** , asigna un nombre de stack-name diferente a los que creaste con las preguntas.

**Comment by tsanborn19** [comment]
I am running into this issue as well. I am happy to help provide more information if anyone is interested in trying to fix this.

After I run `sam pipeline bootstrap` and `sam pipeline init` which creates the stacks for the stages, and add corresponding config files, I then run the `sam deploy ...` command to create the stack with the full pipeline in CodePipeline. The build fails the first time due to not having permission from Github. I then give permission in Github so it can pull the repo. I retry the build, which then will succeed in creating my serverless function and api. However, once it is done, it then triggers an UPDATE_COMPLETE_CLEANUP_IN_PROGRESS event in cloudformation, which causes the Pipeline CodeBuild job to be deleted.

**Comment by bogdan-romaniv** [comment]
I am running into this problem as well. I follow the same steps as @tsanborn19. 
1 - `sam pipeline bootstrap`
2 - `sam pipeline init`

The build fails the first time due to not having permission from Github.  When GitHub permission is given, I can retry the build, which will succeed. But after the deployment, CodePipeline and CodeBuild resources are deleted.

The capture of CloudFormation Events logs.

![image](https://user-images.githubusercontent.com/26332544/198058617-834f6734-7326-410b-b9d4-918408afd497.png)

**Comment by dorlanpabon** [comment]
Compañeros, hay algo que pude evidencia un tiempo, el nombre del stage que se pide en el sam deploy, no puede ser el mismo que los stage creados, pues eso es lo que ocasiona la sobrescritura y eliminación de la pila

**Comment by bogdan-romaniv** [comment]
Thanks, @dorlanpabon. It's what you said. Don't set the same stack name as your SAM application because doing so will overwrite your application's stack (and delete your application resources).

**Comment by dorlanpabon** [comment]
With pleasure

**Comment by hnnasit** [comment]
Resolving this issue as it looks like the problem here was setting the stack name to this prompt `What is the sam application stack name for stage` to be same as either the managed stage pipeline resources stack name that deploys the stage resources or the CodePipeline stack name used to deploy codepipeline.yaml. Setting this stack name would overwrite the deployed stacks when the CodePipeline is executed, and the existing pipeline resources would be deleted. Thanks @dorlanpabon for pointing this out too. For reference, here are the docs on how the naming of the stacks can be done [generating pipeline for AWS CodePipeline](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-generating-example-ci-cd-codepipeline.html) and [tutorial](https://aws.amazon.com/blogs/compute/introducing-aws-sam-pipelines-automatically-generate-deployment-pipelines-for-serverless-applications/). Please let us know if you have more questions or concerns.
