### ISSUE TITLE
Lambda SAM deploy with fixed ImageUri don't deploy even after image rebuild

### ISSUE THREAD

**Issue by gokhanoner** [aws/aws-sam-cli#3870]
### Description:

- have a SAM template for Lambda with container image, with predefined ImageUri
- Build the image & deploy the lambda, it works for the first run, since lambda doesn't exists
- Build the image again & push to ECR with same tag
- Run SAM deploy gets below

```
Initiating deployment

=====================

Waiting for changeset to be created..

No changes to deploy. Stack XXXX is up to date
```

Expected Behavior

- Even if there's no change in the template, since tag is same, my expectation if build will replace the image tag since image hash is changed.
- I believe this is a valid use case, since even if I update the existing tag, it doesn't effect the lambda, as described in update-function-code method -> https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-function-code.html . So deploy should be able to understand that image hash is different between Lambda & repo and deploy again.

Current Behavior

- Nothing happens. Normally deploy fails since there's no change, we're using --no-fail-on-empty-changeset

**Comment by jfuss** [comment]
@gokhanoner Thanks for the issue. This behavior is not controlled by SAM CLI but a mixture of CloudFormation and AWS Lambda. I can't find docs but my understand this is expected behavior within CloudFormation. CloudFormation is going to do a check on the resource to see if anything has changed. If something has changed, CloudFormation will call a handler that is responsible for updating the resource. If no change is detected, then CloudFormation skips updating that resource. 

Since you only updated the ECR image and not the template, CloudFormation sees that nothing has changed. 

If you use `sam build` with Lambda Images, this is taken care of for you.

I will keep poking around to see if there are docs I can link to but the above is my understanding and therefore your behavior you are seeing is expected.

**Comment by gokhanoner** [comment]
@jfuss I understand the logic, but here's my point. If SAM can check whether certain image exist or not when deploying, during deployment, you can also store the digest of the Docker tag & compare with that as well, additionally so if you realize that even though the tag name is same but updated version, it should still deploy. Again, this is what I think it should do!

**Comment by jfuss** [comment]
@gokhanoner Where does the digest of the Docker tag gets stored? 

`sam build` will handle building the image and putting the tag into the template for you. This gives you the desired behavior. If you are side stepping `sam build`, you have to provide the ImageUri and need to care about the tagging. I am not sure I understand your desired state and why not just use `sam build`?

**Comment by moelasmar** [comment]
Hello @gokhanoner, thanks for raising this issue. We will close this issue as there is no active discussions on it for more than two weeks. If you still have the same concern please open a new issue.
