### ISSUE TITLE
How to re-package template artifacts that exist on S3 bucket to a new S3 bucket

### ISSUE THREAD

**Issue by AlDawoode** [aws/aws-sam-cli#4011]
We have many SAM Templates that stored on our GitHub.
When we run 'sam build' and 'sam package' on a template.yaml, 
sam will upload artifacts to S3 bucket (let's call it first bucket) and it will generate new template called packaged.yaml that point to artifacts that got stored on the first S3 bucket.

We then upload the packaged.yaml to the same location where our artifacts got stored.
So the end result will be something like :
![image](https://user-images.githubusercontent.com/38096714/176135478-42a44910-e11d-4e07-a0f6-d6c1bbc52664.png)

The challenge :
We want to move the packaged.yaml as well as it's artifacts to a new S3 bucket (let's call it the destination bucket).

For example i tried to download the packaged.yaml as well as it's artifacts (from the first bucket) to my local machine and
i tried to run :
`sam package --template-file packaged.yaml --s3-bucket destination-bucket --s3-prefix test/firstService --output-template-file test.yaml`

The command got run successfully ! but it doesn't upload artifacts to the new S3 bucket (destination bucket)
and the generated template (in my case test.yaml) is still same to packaged.yaml.
![image](https://user-images.githubusercontent.com/38096714/176137082-64bf8204-81ab-41ec-9c7a-d774b49df82e.png)

How can we move the template with it's artifacts to new S3 bucket (and make the template point to the new artifacts location) ?

**Comment by hawflau** [comment]
Hi @AlDawoode, since you ran the `sam package` command with `--template-file packaged.yaml`, and because `packaged.yaml` already got the `CodeUri` overwritten with the s3 path of uploaded assets, SAM CLI won't recognize that `CodeUri` is something that needs to be uploaded. Nor does it move things from one S3 bucket to another and update your template. 

Can you just run `sam package` without specifying `--template-file`? This will default to the local built template along with other built artifacts.

**Comment by AlDawoode** [comment]
@hawflau  Thanks for your response.
That doesn't help because we don't have the local built template.yaml stored on the first S3 bucket.
What we have on the first S3 bucket are packaged.yaml and it's artifacts.

I think we need to redesign the CI/CD pipeline we have.
