### ISSUE TITLE
Trouble getting a C# lambda function to trigger off of a Kinesis event

### ISSUE THREAD

**Issue by traviscalley** [aws/aws-sam-cli#4047]
Hello,

I am using SAM in C# and Visual Studio. I am trying to update the "serverless.template" file to use a function I am working on to trigger by a Kinesis Event. I would like to run the AWS lambda function locally for development and trigger it by the Kinesis Data Stream in AWS. I am having trouble getting the LambdaEntryPoint.cs to recognize my lambda function and register the endpoint.

I was able to get everything working locally when my trigger was an HTTP POST request. I have been unsuccessful in getting the trigger to work with a Kinesis Event.

**Comment by mndeveci** [comment]
@traviscalley if you are trying to invoke your local lambda by a Kinesis Event which you [configured through events of serverless function resource](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-kinesis.html), then you won't be able to do that since Kinesis service can only invoke that for a regular running lambda function in the cloud. You can run lambda or ApiGW locally, it will work since you are invoking by setting endpoint to localhost there.

For your use case, I would recommend giving a try to [SAM Accelerate](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/accelerate.html) which gives you fast feedback loop while developing your lambda function in your cloud account. In that way, you can configure your Kinesis event to trigger a deployed lambda function. You can make changes to your function, deploy it quickly and iterate.
