### ISSUE TITLE
feat: Addition of command to perform SAM template transformations locally (including PR)

### ISSUE THREAD

**Issue by Crvanetten15** [aws/aws-sam-cli#4060]
## Description
Currently when working with SAM templates retrieving a transformed template is possible using the following commmand:
```sam validate --template {example.yaml} --region {given_region} --debug```
 
 This will return not only the transformed template but also debugging information. It is also required for any `validate` command options that the user has AWS credentials active to run a validation on a SAM template. 

With current commands it is not possible to perform a local transformation of SAM template that only returns the needed output without credentials.

## Proposal
Adding a command that would allow the user to run a local transformation of their SAM template that only returns the output without needing credentials.

## Additional Details
In addition to this post, I have submitted a [pull request](https://github.com/aws/aws-sam-cli/pull/4045) that has a implemented a `transform` command and added it to `aws-sam-cli`. It bypasses the need for AWS credentials, and returns the transformed template.

**Comment by jfuss** [comment]
@Crvanetten15 Thanks for submitting this. It's easy to have a discussion in Issues before PRs and also means less wasted time on code.

Why do you need the transformed templates locally? Is this for debugging, understanding, something else?

On the credential part:
We are not going to be able to provide a command that transforms without needing credentials. This is not a requirement of `sam validate` because validate needs it but more that the `aws-sam-translator` [package](https://github.com/aws/serverless-application-model) itself needs credentials. There are two cases for this 1) Any `AWS::Serverless::Application` resources makes calls to the Serverless Application Repository 2) To get a full list of Managed IAM Policies that is used during the translation process. 1 is conditional while 2 is not. Meaning for `sam validate` or your proposal would require credentials in order to work properly.

**Comment by moelasmar** [comment]
Closing given no response
