### ISSUE TITLE
Require wheel package as part of install

### ISSUE THREAD

**Issue by Jasonca2** [aws/aws-sam-cli#4092]
There are a lot of python dependencies out there that require the wheel package to be installed in order to successfully build when calling `sam build` or `sam package`. Could the `aws-sam-cli` require `wheel` as part of the install and call it from within the same environment? This would greatly simplify the install process.

**Comment by jfuss** [comment]
@Jasonca2 Trying to understand the request here. I don't think `sam package` matters because no building happens within that command. To be simple, `sam package` zips up folders and uploads them to S3. 

For the `sam build` case, this will not work in all instances. So the issue arises when the python interpreter SAM CLI uses to run and the interpreter you want for your function. Instead of packaging, we could install `wheel` but this messes with customer's interpreters and we run the risk of changing something that messes with other packages they have installed. Unless there is another way, I don't think installing is the best option here for SAM CLI.

**Comment by sriram-mv** [comment]
@jfuss assessment above stands. I'm going to close this issue and if you feel there is still some value to exploring this further, we could re-open it.
