### ISSUE TITLE
ERROR install SAM CLI in Alpine container

### ISSUE THREAD

**Issue by rohits2290** [aws/aws-sam-cli#4221]
Followed documentation to install SAM CLI - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

Error message - ./sam-installation/install: line 73: /tmp/sam-installation/dist/sam: not found

Docker container - python:3.9-alpine
Download Zip file for x86_64, unzip and run installer.

RUN cd /tmp \
    && wget  https://github.com/aws/aws-sam-cli/releases/download/v1.56.1/aws-sam-cli-linux-x86_64.zip \
    && sha256sum aws-sam-cli-linux-x86_64.zip \
    && unzip aws-sam-cli-linux-x86_64.zip -d sam-installation \
    && sudo ./sam-installation/install \
    && /usr/local/bin/sam --version

Has anyone come across this error before? Thanks

**Comment by mndeveci** [comment]
Hi there,

Thanks for raising this issue. The problem is coming from the alpine image, it uses `musl` instead of `libc`. Because of that, our native executable can't run in alpine images. I saw there are some workaround mentioned in this page (https://wiki.alpinelinux.org/wiki/Running_glibc_programs) but they didn't work so far.

I can recommend following options to unblock you;
1. Try using a different image which uses `libc`.
2. Try installing through pypi with dedicated virtual environment to SAM CLI.

**Comment by rohits2290** [comment]
Interesting, I used a ubuntu container, seems to be have installed fine.

I tried installing the command using pipx. Still unable to get it working though. The subprocess isn't able to call the installer which the pipx environment.

Anyway, thanks for checking

**Comment by EloB** [comment]
@mndeveci If I install using `pip install` it works but using the zip file and instructions from the webpage I'm getting:

```sh
/bin/sh: sam: not found
```

Even though the file exists.
