### ISSUE TITLE
Sam Deploy Validation Error

### ISSUE THREAD

**Issue by hasnainhakim** [aws/aws-sam-cli#4230]
I received the following error when attempting to deploy my lambda application. My issue is that I am not able to understand what it is asking me to do in order to fix the error.

Initiating deployment
=====================
Uploading to 18fdc6e50e3de5271ca929bd9190af10.template  5195 / 5195  (100.00%)
Error: Failed to create changeset for the stack: talcott-sfn-dev-sam, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-1:027619007323:stack/talcott-sfn-dev-sam/f76050d0-3378-11ed-96f8-127c41fefec1 is in ROLLBACK_COMPLETE state and can not be updated

Could someone please clarify this for me

**Comment by moelasmar** [comment]
I think there is an issue in the template you are using for deployment. Can you try to run `sam validate` to know what is wrong in the template?

**Comment by hasnainhakim** [comment]
Hj Thanks for the reply I run the command and got this response : 

2022-09-15 07:56:17 Loading policies from IAM...
2022-09-15 07:56:21 Finished loading policies from IAM.
C:\Users\hhakim\new project\template.yaml is a valid SAM Template

**Comment by moelasmar** [comment]
sorry @hasnainhakim I missed the issue last time I checked this issue. Your issue is the current deployment stack is in state `ROLLBACK_COMPLETE` which means it failed during the stack creation, and now it is a just empty stack. I suggest to delete it, and then you can recreate it.
You can find the details of this status [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html)

**Comment by sriram-mv** [comment]
Closing this issue as @moelasmar has explained the status code and what to do with the next steps.
