### ISSUE TITLE
Question about using the new esbuild options for nodejs vs lambda layers

### ISSUE THREAD

**Issue by ptejada** [aws/aws-sam-cli#4250]
I started a project with the TypeScript template and the default esbuild config an minifcatoin really reduces the size of your lambda functions. However, there is also the common practice of creating a lambda layer for your nodejs dependencies. When a lambda layer is used its overall size is a lot bigger because all the nodejs modules are included in full along with all the none code files.

For comparison, the standalone layer can be up to 16MB alone while the minified esbuild bundle for the whole function is only ~2MB.

I am curious as to what is the better or most efficient approach to handle nodejs dependencies in lambda functions now.

**Comment by mildaniel** [comment]
I would say that for third-party dependencies, letting them be tree-shaken and minified is the best approach since you'll get the smallest bundle size. Like you said, it'll likely be a lot smaller than having the entire dependency tree included. If ever you don't want to include a dependency with the bundled deployment, you can mark it as external and reference it through a layer. 

For shared code or first-party libraries, using layers is probably still the best approach so that you can make changes to them independently of the Lambda function. It's a trade-off between modularity and deployment size. Pick whichever method works best for you given your use case.

As an aside, if you want to use a layer for all of your dependencies, you can mark them all as external by setting an element in the external property in your template to `./node_modules/*`.

**Comment by ptejada** [comment]
Thank you for the tips
