### ISSUE TITLE
Bug: sam local start-api doesn't recognize parameter_overrides in toml files

### ISSUE THREAD

**Issue by tunesmith** [aws/aws-sam-cli#4348]
### Description:
`sam local start-api` doesn't recognize parameter_overrides in toml files.

### Steps to reproduce:
This works:

`sam local start-api --parameter-overrides key1="val1" key2="val2"`

This doesn't work:

`sam local start-api --config-file=sam-configs/qa.toml`

where sam-configs/qa.toml is:

```
version = 0.1

[default.deploy.parameters]
[...]
parameter_overrides = [
    "key1=val1",
    "key2=val2",
]
```

Note that `sam deploy --config-file=sam-configs/qa.toml` *does* work.

It also doesn't work if sam-configs/qa.toml is:

```
version = 0.1

[default.deploy.parameters]
[...]
parameter_overrides="ParameterKey=Key,ParameterValue=Value ParameterKey=Key2,ParameterValue=Value2"
```

### Observed result:
In my case the key pair that is not being recognized is DbSecretIdParam with an arn value. As said, it does work with the --parameter-overrides CLI flag.

### Expected result:
`sam local start-api` should work with `--config-file`, as `sam deploy` does.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 1.61.0
3. AWS region: us-east-1

`--debug` includes this in its output:

```
Collected default values for parameters: {}
```

**Comment by mndeveci** [comment]
Hi there,

This an expected behaviour because `samconfig.toml` (or other configuration `.toml` files)  keep these configuration per command. What you have in your file is specific to `sam deploy` command. Other commands won't use these values. If you want to have defaults for `sam local start-api`, you need to copy these values under new table. So you need something like this;

```
version = 0.1

[default.deploy.parameters]
parameter_overrides="ParameterKey=Key,ParameterValue=Value ParameterKey=Key2,ParameterValue=Value2"
....
[default.local_start_api.parameters]
parameter_overrides="ParameterKey=Key,ParameterValue=Value ParameterKey=Key2,ParameterValue=Value2"
```

You can read more about structure of config file here; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

Please let us know if you have any other questions.

**Comment by tunesmith** [comment]
Thank you for the pointer! I will close.
