### ISSUE TITLE
Bug: Generated pipelines from sam pipeline for dotnet 6 don't work and have little guidance

### ISSUE THREAD

**Issue by bzuillsmith** [aws/aws-sam-cli#4422]
### Description:

When generating a pipeline for Bitbucket and dotnet 6 with SAM Pipeline, the template generates using the command `sam build --template $SAM_TEMPLATE --use-container` but should leave out the `--use-container` option as it is unsupported in this scenario.

This also means that the dotnet cli must be installed. It would be wonderful to include a step installing this. I have attempted with

    - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --version latest
    - sam build --template $SAM_TEMPLATE

but `sam build` fails to find the dotnet cli. I'm not sure what I'm missing or if there is a better approach.

### Steps to reproduce:
Run sam pipeline for a dotnet 6 project on bitbucket
Push the project

### Observed result:
Using generated template
![image](https://user-images.githubusercontent.com/1412248/202298369-18c0d45b-09aa-432e-a5af-cfa236a69908.png)

After removing --use-contianer option
![image](https://user-images.githubusercontent.com/1412248/202298522-985aef49-5413-47fb-8975-956ebd1f6b43.png)

After installing dotnet 6 sdk and running sam build
![image](https://user-images.githubusercontent.com/1412248/202298643-b1ced3fb-cb0e-4072-b2b9-3040137f0630.png)

### Expected result:
For it to work from the generated template or at least to be told clearly the limitations and how to modify it.

**Comment by bzuillsmith** [comment]
After further investigating, I found it was using the wrong image. It had generated the pipeline with `public.ecr.aws/sam/build-provided` which I guess is for a custom build environment rather than `public.ecr.aws/sam/build-dotnet6`. I'm not 100% sure if I chose an option to make that happen, or if it was the default.

**Comment by xazhao** [comment]
Hello! The image of SAM Pipeline uses is here: https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/Bitbucket-Pipelines/two-stage-pipeline-template/%7B%7Bcookiecutter.outputDir%7D%7D/bitbucket-pipelines.yml#L1

Right now `sam pipeline` can only use the custom build environment which is why dotnet cli is not installed. The proper workaround would be the adding dotnet cli installation to the pipeline file generated.

**Comment by bzuillsmith** [comment]
Okay, why though? Correct me if I'm wrong, but it seems like the whole purpose of the same pipeline command is to make a ready and working template. As it is now, it is not ready and working and there is very little guidance as to how to get it working for the scenario of using it with .net.

It seems like you've identified the source of the limitation that currently has, so I guess my question is can we make it better? 

Removing the --use-container arg and replacing the image on the first line with the image that I mentioned previously seem to be all I needs to make it working. But that was not obvious by any of the docs and it took me hours to figure out. It would not take much to and this guidance to some docs. But an even better solution in my mind would be to make the template more dynamic and actually make it working from the script and then offer guidance for more custom scenarios.

**Comment by bzuillsmith** [comment]
Also, I attempted to add the dotnet cli to the script manually and still got a failure as documented above. It wasn't until I replaced the image on the first line with the dotnet specific one that it worked.

**Comment by xazhao** [comment]
Sorry @bzuillsmith I misunderstood what you meant. Your way of changing image and removing `--use-container` is the correct way.

We decided to use `public.ecr.aws/sam/build-provided` and `--use-container` because it's more generic. If you only use a single runtime, then just replace the image and remove `--use-container` option.

I do agree that if we could use a dynamic way to use proper image, it would be a better experience. However this may need another prompt to ask for runtime. I will create a feature request and discuss with the team. 

I can add a comment at the line of `image` so it would be easier to get this information for now.

**Comment by xazhao** [comment]
You mean `sam init` asked for the runtime when it fetches the template? It might work but I don't feel it's reliable to read the value from the template to decide the runtime (template could be really complicated). What I prefer is to have a way to specify runtime when generating pipeline templates. Let me know your thoughts.

**Comment by bzuillsmith** [comment]
Ah yes, you are right. I forgot when exactly it asked for the runtime. What you're saying makes sense

**Comment by xazhao** [comment]
Thanks! Creating a feature request internally and resolving this issue. Feel free to re-open this issue if you have more questions.
