### ISSUE TITLE
Feature request: support Finch for container related workflows

### ISSUE THREAD

**Issue by dreamorosi** [aws/aws-sam-cli#4584]
### Describe your idea/feature/enhancement

[Finch](https://github.com/runfinch/finch) is an open-source container runtime client for MacOS that has been published by AWS and has an Open Source license. Finch's command-line syntax is not 100% compatible with that of `docker` but is quite close.

In anticipation of broader adoption of the tool by the community, SAM CLI could support it for all container-related workflows as a Docker replacement.

### Proposal

At the moment there are certain workflows (i.e. `sam invoke local`) that require a `docker` daemon running on the host machine. It would be great if the SAM CLI could add support to `finch` either via flag or by transparently checking which one of the two engines is available and use that one (if both available default to one).

This won't require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model).

### Additional Details

Finch Launch Blog post: https://aws.amazon.com/blogs/opensource/introducing-finch-an-open-source-client-for-container-development/
Video: https://www.youtube.com/watch?v=S7JwFFZ-7_Q

**Comment by mndeveci** [comment]
Hi there,

We are working closely with Finch team about SAM CLI support. Since they are compatible with Docker APIs, using Finch with SAM CLI only requires updating `DOCKER_HOST` environment variable to point the Finch socket file. SAM CLI commands should work as expected.

You can either set it per process; `DOCKER_HOST=/path/to/finch/socket/file sam local invoke`
or set it for the terminal session; `export DOCKER_HOST=/path/to/finch/socket/file`

If you experience any problems using SAM CLI with Finch, please feel free to create GH issues on their repo or on ours.

**Comment by monirul** [comment]
Hi,
Unlink docker, Finch does not expose any unix socket. Since SAM CLI uses docker py which rely on the unix socket to communicate with docker engine, SAM CLI will not work with finch.
