### ISSUE TITLE
Bug: Need to tag a file in --tags section for SAM Deploy Command 

### ISSUE THREAD

**Issue by aneelaanee** [aws/aws-sam-cli#4610]
### Description:
 I have created a dev.json file-> where all the tags were stored .. I need to refer dev.json file in Sam deploy command for --tags section 

It is throwing this Issue 
Try 'sam deploy -h' for help.
Error: Invalid value for '--tags': ('file://./tags/dev.json',) is not in valid format. It must look something like 'KeyName1=string KeyName2=string'

### Expected result:
I need to --tags to refer to dev.json file 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by qingchm** [comment]
@aneelaanee Hi there since --tags flag do not support json input this is expected behaviour. In order to use this tags flag either provide command line arguments like `--tags="Tag1=something Tag2=something"` or save it to samconfig.toml in the form of deploy configs.
One example:
```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
tags = "stage=int company:application=awesome-service company:department=engineering company:staff=12"
```
or another
```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
tags = [
    "stage=int",
    "company:application=awesome-service",
    "company:department=engineering",
    "company:staff=12"
    ] 
```
If you still think json file input is necessary, feel free to open a feature request supporting this feature.
