### ISSUE TITLE
Bug: sam deploy - NoCredentialsError

### ISSUE THREAD

**Issue by jwarmkessel** [aws/aws-sam-cli#4646]
### Description:
I'm setting up a demo following these steps here: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat#deploying-the-solution. 

When I run 'npm run deploy' I get this error: An unexpected error was encountered while executing "sam deploy".

### Steps to reproduce:
Follow the steps of the demo to reproduce.

### Observed result:
An unexpected error was encountered while executing "sam deploy".

### Expected result:
No errors.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ventura 13.2
2. `sam --version`: SAM CLI, version 1.71.0
3. AWS region: West (I wonder if the problem is that the tutorial specifies East but the yaml configuration specifies West.)

```
# Paste the output of `sam --info` here
```
{
  "version": "1.71.0",
  "system": {
    "python": "3.11.1",
    "os": "macOS-13.2-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

`Add --debug flag to command you are running`

**Comment by torresxb1** [comment]
Hi @jwarmkessel, from the title it seems like you might not have set up aws credentials properly. The SAM CLI needs to be able to find your aws credentials in order to deploy. Take a look at:
- https://docs.aws.amazon.com/cli/latest/userguide/getting-started-prereqs.html
- https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by jwarmkessel** [comment]
Resolved the issue. Region was set to West not East. Thank you for the quick turnaround on this.
