### ISSUE TITLE
Bug: Cloud Endpoints doesn't show API Gateway domain name

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli#4670]
### Description:

In terms of developer experience, if you don't use Route53, it's very cumbersome to see the endpoint to configure your DNS provider with! https://twitter.com/praneetaprakash/status/1621327393804914696

Currently you need to dig it out the AWS console:

<img src="https://s.natalian.org/2023-02-08/custom-domain-name-endpoint-configuration.png">

### Steps to reproduce:

https://github.com/kaihendry/helloworld update the DOMAINNAME and ACMCERTIFICATEARN in https://github.com/kaihendry/helloworld/blob/master/Makefile

### Observed result:

https://s.natalian.org/2023-02-08/sam-list-endpoints.txt

### Expected result:

`sam list endpoints` to show the actual **API Gateway domain name**, in my case d-908ajvn73h.execute-api.ap-southeast-1.amazonaws.com

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
# Paste the output of `sam --info` here
{
  "version": "1.72.0",
  "system": {
    "python": "3.7.10",
    "os": "Linux-6.1.9-arch1-2-x86_64-with-arch"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "1.2.9"
  }
}
```

https://s.natalian.org/2023-02-08/sam-list-endpoints.txt

**Comment by jfuss** [comment]
@kaihendry Thanks for the issue. I am still trying to understand our code as there seems to be logic targeting this use case: https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/list/endpoints/endpoints_producer.py#L392. There is some interesting output from your command run too: `2023-02-08 15:11:48,032 | There is no customer defined id or cdk path defined for resource ApiGatewayDomainNameV260ef7d66a0, so we will use the resource logical id as the resource id`. So it looks like it got ignored "somewhere". I need to dig a little deeper and sync up with someone on the team that is more familiar here than I am.

As an alternative, you could use the Stack Outputs and reference the generate DomainName resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-httpapi.html#sam-specification-generated-resources-httpapi-domain-name. `Ref: <httpapi‑LogicalId>.DomainName` should get you the info you want (reading https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-domainname.html#aws-resource-apigatewayv2-domainname-return-values). Then using `sam list stack-outputs` would get you the info in the command line without going to the console.

**Comment by kaihendry** [comment]
Sorry @jfuss ... I'm not how to adjust https://github.com/kaihendry/helloworld/blob/master/template.yml ... do you have a snippet? I've tried a bunch of things which don't work.

**Comment by jfuss** [comment]
@kaihendry No need to be sorry!

If I am understanding everything correctly, the following in the `Outputs`
```
GatewayEndPoint:
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
```

needs to be:
```
GatewayEndPoint:
    Value: !Ref Gateway.DomainName
```

Then `sam list stack-outputs` should give you the ability to get the `GatewayEndPoint` with the value of the DomainName on Api Gateway.

**Comment by kaihendry** [comment]
Got this error:

```
❯ make sam-list-endpoints
sam list stack-outputs --stack-name helloworld-sam

Error: 'Description'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 150, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/_utils/command_exception_handler.py", line 40, in wrapper_command_exception_handler
  File "samcli/commands/_utils/command_exception_handler.py", line 25, in wrapper_command_exception_handler
  File "samcli/commands/list/stack_outputs/command.py", line 40, in cli
  File "samcli/commands/list/stack_outputs/command.py", line 52, in do_cli
  File "samcli/commands/list/stack_outputs/stack_outputs_context.py", line 45, in run
  File "samcli/lib/list/stack_outputs/stack_outputs_producer.py", line 66, in produce

An unexpected error was encountered while executing "sam list stack-outputs".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20list%20stack-outputs%20-%20KeyError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20list%20stack-outputs%20-%20KeyError
make: *** [Makefile:30: sam-list-endpoints] Error 1
```

**Comment by kaihendry** [comment]
Thanks but still doesn't print out **d-908ajvn73h.execute-api.ap-southeast-1.amazonaws.com** and btw the data in OutputValue column makes it ... challenging to copy/paste.

```
sam list stack-outputs --stack-name helloworld-sam
Stack Outputs
------------------------------------------------------------------------------------------------------------------
OutputKey                              OutputValue                            Description
------------------------------------------------------------------------------------------------------------------
HelloLogs                              sam logs --name Hello --region ap-
                                       southeast-1 --tail
Hello                                  arn:aws:lambda:ap-southeast-1:407461   First Lambda Function ARN
                                       997746:function:Hello
HelloIamRole                           arn:aws:iam::407461997746:role/hello   Implicit IAM Role created for Hello
                                       world-sam-HelloRole-1JDD7FTGK3S8       World function
GatewayEndPoint                        hellosam.dabase.com
------------------------------------------------------------------------------------------------------------------
```

**Comment by jfuss** [comment]
@kaihendry You can provide the `--output json` to the command. Will also make scripting easier. That option defaults to `table`.

Maybe that is the Region Domain Name then? I normally don't have to deal with these resources, so I am likely just as confused on all the properties.

If it is the Regional Domain Name, it doesn't look like [SAM](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-httpapi.html#sam-specification-generated-resources-httpapi-domain-name) surface that `FN:GetAtt` from SAM directly. Which is something else we should address here.

You could directly hardcode the logical Id of the DomainName generated, but if that changes (since it's generated by SAM) you are stuck again. The other option, could be to possible script this so you can query API Gateway directly. I am really just trying to think of ways to fully unblock you and not have you jump to the console at all. 

I did chat with the team yesterday, and this should work as you originally wanted. We need to do a deeper dive to understand why it isn't. It could be this regional Domain Name part if that ends up what you are actually trying to get at here. Regardless, your repo with the example will really help us do that. So thank you for providing it!

**Comment by kaihendry** [comment]
I tried to make a #speedrun of a SAM deployment and this part trips me up. https://youtu.be/Zkne02QhcDk?t=559

I also found that if I wasn't careful to rename some resources in https://github.com/kaihendry/helloworld/blob/master/template.yml it could cause conflicts with other stacks. Maybe I'm going mad.

Nonetheless the developer experience of such a simple use case desperately needs to improve in AWS SAM. It's holding back Serverless adoption.

**Comment by jfuss** [comment]
We appreciate the feedback @kaihendry. I know you have been very vocal in the past as well, which we love. 

I don't want to distract for the originally issue but feel it is important to at least respond.

> I also found that if I wasn't careful to rename some resources in https://github.com/kaihendry/helloworld/blob/master/template.yml it could cause conflicts with other stacks. Maybe I'm going mad.

This is a restriction that comes from CloudFormation and the resources that get created. In your example, since you named your function directly with a hardcoded value, other stacks of the same template or that define the same Name in another Lambda function will collide. This causes naming conflicts, which AWS Services will reject. Best practice with CloudFormation is to let the CloudFormation service name the resources. There are services that require Names and in those cases, it best to do a `!Sub` with Parameters or the StackName to help avoid this issue.

While that describes the issue and what is happening, you (and others) are left to find this late in cycles which causes issues. Pretty recently, the team was talking about this exact thing. We thought about adding CFN Lint rules or do something like Warnings in SAM CLI directly but I don't think we have a good sense of what the right thing is here but I know we do recognize the problem.

> Nonetheless the developer experience of such a simple use case desperately needs to improve in AWS SAM. It's holding back Serverless adoption.

We have various projects/improvements this year centered around UX (see https://github.com/aws/aws-sam-cli/wiki/AWS-SAM-CLI-Roadmap#user-experience). I would say keep the feedback coming. We are trying to push the feedback more into discussions, so I would encourage you to create threads there for any follow ups.

I know this isn't the best answer, but my goal was to hopefully communicate these are areas we are actively working on. The more community feedback from customers like yourself, the more signals we get that help us focus on specific areas. So from the team, thank you for being active in the community and spending the time to give us feedback!

**Comment by kaihendry** [comment]
Thanks @jfuss ... is https://github.com/kaihendry/helloworld/commit/d2fc20a753b10397079f081dc39a90b325b6dd20 enough?

I'm not sure how to "create threads" upon https://github.com/aws/aws-sam-cli/wiki/AWS-SAM-CLI-Roadmap#user-experience .. via https://github.com/aws/aws-sam-cli/discussions ?

Thank you again for your earnest response.

**Comment by jfuss** [comment]
> Thanks @jfuss ... is https://github.com/kaihendry/helloworld/commit/d2fc20a753b10397079f081dc39a90b325b6dd20 enough?

That is enough. If you don't need a specific name, you could remove `FunctionName` completely. CloudFormation will create a name with the LogicalID within it. That could be enough for you as well but at the very least the way in the commit should give you name isolation you want.

> I'm not sure how to "create threads" upon https://github.com/aws/aws-sam-cli/wiki/AWS-SAM-CLI-Roadmap#user-experience .. via https://github.com/aws/aws-sam-cli/discussions ?

I should have linked this from the start. https://github.com/aws/aws-sam-cli/discussions/4689 is the discussion thread for our roadmap. There you can leave comments and respond in threads. I don't think you can create direct comments within the Github wiki.

**Comment by kaihendry** [comment]
Removed FunctionName and then I hit `Replacement type updates not supported on stack` when trying to deploy. These are the pain points you need to address. Once in an **UPDATE_FAILED** state I wasn't sure how to progress, other than just going into the console and deleting the stack like I did before: https://youtu.be/Zkne02QhcDk?t=569

And then the same rigamorale of updating the CNAME with the domain that can only be fetching out of the console's API Gateway. :cry: 

It would be great if SAM could somehow reduce these seven lines:

      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY

**Comment by jfuss** [comment]
> hit `Replacement type updates not supported on stack` when trying to deploy

This is due to you providing `--disable-rollback` in the deploy command. This error is a restriction imposed by CloudFromation. So you providing the option (which I think is only on create-stack), tells SAM CLI to set it. Not sure what you are looking for SAM CLI do to in this case.

**Comment by kaihendry** [comment]
Sorry, just to reiterate to confirm my understanding: If I had an existing FunctionName name set, and I wanted to refactor and remove it to simplify my template, I would have to delete / recreate the stack?

**Comment by lucashuy** [comment]
Sorry about the delay in response. That is correct, if `--disable-rollback` was passed, replacement operations on resources that might have changed will not be allowed. Future changes to the template that involve a replacement will likely have to be redeployed as a new stack.

As for the original issue, `sam list endpoints --stack-name <stack>` not returning the correct custom domain name when using parameters appears to be an edge case. Since there is no default value for the `Parameters` in the template, SAM CLI is not able to resolve the correct domain name (`!Ref DomainName` will never resolve, thus SAM CLI won't be able to find the correct resource).

As a work around, you can set the default domain name and SAM CLI should be able to resolve the correct custom domain.
```
Parameters:
  DomainName:
    Type: String
    Default: my-custom-domain.tld
```

We can take in the second part as a feature request. SAM CLI does not currently list the API Gateway domain name (the one that is highlighted) that gets generated when a custom domain is added, so we can add this to the endpoints output.

**Comment by kaihendry** [comment]
@lucashuy I'm confused since `!Ref DomainName` only tells me what I already know.

![image](https://user-images.githubusercontent.com/765871/236373100-7599ec42-0888-458b-9a18-0b90d4431ab4.png)

I want the **API Gateway domain name** please.

**Comment by lucashuy** [comment]
Hi, thanks for replying. We don't currently surface this information with `sam list`. We'll have to see if we can expose this attribute through SAM, or if it makes sense to include this in the output of `sam list endpoints`.

The original comment about the parameter is a workaround for an edge case regarding parameters and the `sam list` command. Since there isn't a way to actually override the parameters in the template when running `sam list`, the parameters will never resolve correctly if there isn't a default value set. This is a different issue than getting the API Gateway domain name however.

**Comment by lucashuy** [comment]
Thanks for waiting, as for getting the regional domain name (the one highlighted) can you try modifying the following in the provided template:

```yaml
Outputs:
  regional:
    Description: The regional domain name for CNAME value
    Value: !GetAtt [Gateway.DomainName, RegionalDomainName]
```

This should let you get the regional domain name as part of the outputs from the stack.

**Comment by kaihendry** [comment]
It works! Omg, something that I've wanted for years is now addressed. 🎉  https://github.com/search?q=%22%5BGateway.DomainName%2C+RegionalDomainName%5D%22&type=repositories
https://dabase.com/blog/2023/sam-developer-experience/#no-way-to-see-the-cname-api-once-deploying

It makes me wonder am I the only one using a regional domain name? Am I doing it wrong? 😅

**Comment by lucashuy** [comment]
Nope, you aren't the only one that wants to get the regional domain name from their deployed resources, so this is a completely valid use case :smile:

There are a couple of issues over on the Serverless Application Model repository asking about the same thing (which is where I got the above suggestion from!)

**Comment by kaihendry** [comment]
Could you link the issues for completeness please? I don't see anyone else using it after a search on Github.

**Comment by lucashuy** [comment]
Hi, this is one of the issues from the Serverless Application Model repository that discusses this: https://github.com/aws/serverless-application-model/issues/1386
