### ISSUE TITLE
SAM accelarate - Lambda layers

### ISSUE THREAD

**Issue by farzana-juthi** [aws/aws-sam-cli#4791]
## Description: 
I tried to get python library from lambda layers. This code works when I run it through codepipeline. But when I tried it from SAM accelerate( sam sync), it did not work.  aws_lambda_powertools did not saved into .aws-sam dependency layer folder, so when I tried to get it into the lambda layers function, I got an error.

<img width="1206" alt="Screenshot 2023-03-01 at 11 00 28 AM" src="https://user-images.githubusercontent.com/63281366/222049303-7c576882-4db2-4786-90ca-cdc65591bb6c.png">
<br/>

### Projects Structure:

<img width="357" alt="Screenshot 2023-03-01 at 10 47 26 AM" src="https://user-images.githubusercontent.com/63281366/222047330-92f71dcd-9113-437a-9030-8a82fc2f1e95.png">

### Template file:

<img width="412" alt="Screenshot 2023-03-01 at 10 52 16 AM" src="https://user-images.githubusercontent.com/63281366/222047919-44ece975-ac96-4b27-9f14-991bfc14bdab.png">

### Make file:

<img width="710" alt="Screenshot 2023-03-01 at 10 53 54 AM" src="https://user-images.githubusercontent.com/63281366/222048094-af89ee5f-36f9-4754-8e7c-f04fc9e95bb9.png">

## Observed result:
When I run `sam sync --watch --stack-name sam-app`
 it shows like that

<img width="628" alt="Screenshot 2023-03-01 at 10 56 01 AM" src="https://user-images.githubusercontent.com/63281366/222048542-16aa1f92-7770-4e43-8302-610eeaf8765c.png">

## Expected result: 
Layers should have libraries what are mentioned in requirement.txt file.

**Comment by hnnasit** [comment]
Hello @farzana-juthi, if I understand this right you want to include aws-lambda-powertools library within the Layer so that it can be imported in the Lambda Function. When the makefile runs, `pip install --default-timeout=100 -r ./python/requirements.txt -t .` command installs all the dependencies in a temporary folder. Instead, if you run `pip install --default-timeout=100 -r ./python/requirements.txt -t $(ARTIFACTS_DIR)/python` this will add the dependencies to `.aws-sam/auto-dependency-layer/GlobalUtils/python` folder and then importing that library in the Lambda Function should work. If you want to use the auto created dependency layer instead of creating a separate dependency layer, you can add the library `aws-lambda-powertools` to `hello_world/requirements.txt` and `sam sync` will automatically build and move the dependency to `.aws-sam/auto-dependency-layer/HelloWorldFunction19d43fc4DepLayer/python`. I have tested this and both the solutions work. Please let us know if you have any further questions or concerns.

**Comment by farzana-juthi** [comment]
Thank you so much @hnnasit . You got me right. I want to do the first approach because I want to use some libraries for every lambda function. Do not want it written multiple times in requirement.txt file for individual lambda. Your solution worked for me. Really helpful.
