### ISSUE TITLE
Bug: sam package error

### ISSUE THREAD

**Issue by wssrronak** [aws/aws-sam-cli#4923]
I am deploy a package using Sam cli. In the package I am creating an APIGateway that are calling lambda function in the backend.

I had successfully return no error from these command which are mentioned below:
sam build 
sam validate 

build and validate it is working working.

But when i write this command

sam package --template-file template.yaml --output-template-file deploy.yaml --s3-bucket s3-sam-data

This package command is through me an error

Error: Unable to upload artifact lambda-layer/ referenced by ContentUri parameter of LambdaLayer resource.
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

Kindly anyone can help me out for this

**Comment by moelasmar** [comment]
Thanks @wssrronak for your question.
It is better to include the full logs of `sam package` command, but I believe the issue is the user/role you are using to run sam command does not have the required permissions to upload the template, and the built artifacts to S3. 

to confirm, you can run the following command to check if you have the required permissions or not:
```
aws s3 cp <any local file path> s3://s3-sam-data
```

also, another comment that is not related to your issue. You should not pass `--template-file template.yaml` to the `sam package` command, as SAM CLI will package this template file instead of packaging the built template (the one generated from running `sam build` command)
