### ISSUE TITLE
SAM existed docker containers pile up

### ISSUE THREAD

**Issue by royassis** [aws/aws-sam-cli#5080]
Hey 

I'm using the SAM cli to build and run image based lambda. 
Now just noticed that I got a lot existed containers piling up, probably due to `sam build --use-container` and/or
 `sam local invoke` .

Roy

**Comment by sriram-mv** [comment]
Hey @royassis , build images once pulled down usually tend to stay on the machine. Similarly for local invoke an image is built with the aws-lambda-rie binary layered on top, those images need to exist for the command to work.

**Comment by sriram-mv** [comment]
What are the kind of images that you see locally? Are they the base build images? Could you share some more details on this front with us to help us debug? Thank you!

**Comment by royassis** [comment]
Hey @sriram-mv 

Just wanted to clarify that i'm talking about **existed containers** and not images.

Here is an output from the prompt. 
```shell
(base) PS C:\Users\roya> docker container ls -a
CONTAINER ID   IMAGE          COMMAND                  CREATED      STATUS                  PORTS     NAMES
59cf294d3250   6a1b8c4385a5   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             keen_thompson
2251bf4863d3   6a1b8c4385a5   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             confident_volhard
b8de2b45358b   6a1b8c4385a5   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             loving_chatelet
ae362394262b   f0144e34c82a   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             naughty_chandrasekhar
125c57138d93   b47f76990662   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             sharp_pascal
46da229e1040   b58d28c0caff   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             strange_jones
9f4ff4fd7852   c0ac7c1d9a61   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             sharp_mahavira
d164e8734e5d   9e4dcb46a40f   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             nostalgic_leavitt
ff1fc69d36f5   9e4dcb46a40f   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             festive_visvesvaraya
39b35dde4438   9e4dcb46a40f   "/bin/sh -c 'pip3 in…"   4 days ago   Exited (1) 4 days ago             keen_clarke
6af8a48897c8   591411ce0b8d   "/bin/sh -c 'pip3 in…"   5 days ago   Exited (1) 5 days ago             strange_colden
```

Best,
Roy

**Comment by mndeveci** [comment]
Looking at table above, these containers look like intermediate ones which is used by docker when running build. We have changed our behaviour to remove them some time ago (see: https://github.com/aws/aws-sam-cli/blob/fab40878bfd2802040c963f00f912e2d81b09d0d/samcli/lib/build/app_builder.py#L411)

And as far as I understand, Docker also changed its behavior to remove these containers (see: https://docs.docker.com/engine/reference/commandline/build/, `--rm` flag's default value is `true`)

My recommendation would be updating SAM CLI to latest version as well as updating Docker installation.

If that doesn't work, please provide steps to reproduce for us so that we can deep dive into it.

Thanks!

**Comment by moelasmar** [comment]
Closing this issue. Feel free to open a new issue if the issue still persists.
