### ISSUE TITLE
How does sam deploy with '--config-env' and '--parameters-overrides' work when both needed?

### ISSUE THREAD

**Issue by CloudedThings** [aws/aws-sam-cli#5169]
Hi
I'm struggling with the sam deploy command and the way how the parameters ought to be provided. 
**My question is how to use the samconfig and cli --parameter-overrides if needed both?**

I've been using the samconfig.toml for storing my template parameters. Nothing special about it:
```
version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "api-staging"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvType=staging",
  ...
]
```
and deploying the stack with `sam deploy --config-env staging`

Then I needed to use a trick to force update the secrets in my lambdas so I added 
`sam deploy --config-env staging --parameter-overrides "Token1ChangeDate=${{ env.TOKEN1_CHNG_DATE }} Token2ChangeDate=${{ env.TOKEN2_CHNG_DATE }}"`

That worked until sometime later I needed to add additional parameters in samconfig file. And when trying to deploy this updated samconfig:
```
parameter_overrides = [
  "EnvType=staging",
  "NewParameter=Value1",
  "NewParameter2=Value2"
]
```
with this command:
`sam deploy --config-env staging --parameter-overrides "Token1ChangeDate=${{ env.TOKEN1_CHNG_DATE }} Token2ChangeDate=${{ env.TOKEN2_CHNG_DATE }}"`

The deployment failed because of:
`Error: Failed to create changeset for the stack: api-staging, An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [NewParameter, NewParameter2] must have values`

I've tried adding the Token1ChangeDate and Token2ChangeDate in samconfig:
```
parameter_overrides = [
  "EnvType=staging",
  "Token1ChangeDate=2023-05-03T14:21:53.419000+00:00",
  "Token2ChangeDate=2023-05-03T14:21:53.233000+00:00",
  "NewParameter=Value1",
  "NewParameter2=Value2"
]
```
But that throws the same error when executing:
`sam deploy --config-env staging --parameter-overrides "Token1ChangeDate=${{ env.TOKEN1_CHNG_DATE }} Token2ChangeDate=${{ env.TOKEN2_CHNG_DATE }}"`

`Error: Failed to create changeset for the stack: api-staging, An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [NewParameter, NewParameter2] must have values`

What I need is a way to be able to add new parameters to samconfig and keep using the --parameter-overrides cli command. How to achieve that?

SAM CLI, version 1.82.0

**Comment by mndeveci** [comment]
Hi there,

Whatever is provided via command line option, will have higher precedence than what you have in `samconfig.toml` file. ([see here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html#rules)). 

For that reason, in order to fix your problem, you need to provide values for (NewParameter, NewParameter2) in your CLI options. Something like; `sam deploy --config-env staging --parameter-overrides "Token1ChangeDate=${{ env.TOKEN1_CHNG_DATE }} Token2ChangeDate=${{ env.TOKEN2_CHNG_DATE }} NewParameter={NewParamVal} NewParameter2={NewParam2Val}"`

Or as an alternative, you can define a new config environment with values that can be used that environment, and you can just provide the environment name rather than the whole config options. With example `samconfig.toml` file below, you can run `sam deploy --config-env staging-extravars`.

`samconfig.toml`
```
version = 0.1
[staging-extravars]
[staging-extravars.deploy]
[staging-extravars.deploy.parameters]
stack_name = "api-staging"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvType=staging",
  "NewParameter={NewParamVal}", 
  "NewParameter2={NewParam2Val}"
]
```

Please let us know if you have further questions.

**Comment by hnnasit** [comment]
Closing this issue as the above response addresses the question. Feel free to open a new issue if you have any further questions.
