### ISSUE TITLE
Bug: Layer defined in yaml using dotnet, but the functions output dir still has all the layer DLLs

### ISSUE THREAD

**Issue by samprakos** [aws/aws-sam-cli#5246]
### Description:
I have defined a layer with BuildMethod = dotnet6.  When I sam build, it builds the layer, then builds my function.  Then I go to the functions output dir (.aws-sam/build/LogHello) and I see all the DLLs in there that also show up under the layer output dir.  When I deploy this function, the code size in aws console is the same as without the layer.

### Steps to reproduce:

1. Unzip the attached dotnet lambda file
2. Navigate to the function dir
3. sam build
4. Go to ./.aws-sam/build/LogHello and see what files are there
5. Deploy the function and look at aws console

### Observed result:
DLLs that are in the layer are also copied into the function output dir

### Expected result:
DLLs that are in the layer should be excluded from the functions output dir

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

{
  "version": "1.84.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-13.2-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.17",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

7. AWS region: us-east1

[lambda.zip](https://github.com/aws/aws-sam-cli/files/11635597/lambda.zip)

**Comment by samprakos** [comment]
There's a project attached to the original post w/ instructions on how to repro.

**Comment by jfuss** [comment]
@samprakos Well that is embarrassing... 🤦‍♂️

I saw "lambda.zip" and assumed it was the lambda function. My bad! And thank you for attaching it in the first place :)

**Comment by jfuss** [comment]
@samprakos I am not super familiar with dotnet but looking at the `Function.csproj` it includes the layer (`<ProjectReference Include="..\Layer\Layer.csproj" />`. So the result you are seeing seems expected.

Likely missing something here due to lack of dotnet knowledge.

**Comment by samprakos** [comment]
Right that Layer.csproj ref is needed to be able to build the function.  I think the missing piece is something that tells `dotnet publish` to exclude certain files, using either `--manifest manifest.xml` or specifying that in the functions csproj file via 

```
  <PropertyGroup>
    <TargetManifestFiles>manifest.xml</TargetManifestFiles>
  </PropertyGroup>  
```
but I'm still researching how to get the Layer.csproj to generate that manifest file so it can be used in the function build step.

**Comment by normj** [comment]
Hi @samprakos 

SAM doesn't have support for creating Lambda layers that are compatible with the .NET runtime. The .NET runtime won't know how to find the assemblies that are in Lambda layer.

In the underlying .NET Lambda CLI tool that SAM uses for packaging .NET Lambda functions it has a separate command for creating Lambda functions. For your project I ran the following command the `Layer` directory to create a .NET Lambda layer.

```
dotnet lambda publish-layer --region <region> --layer-name lambda-layer-test --layer-type runtime-package-store --s3-bucket <s3-bucket> --framework net6.0
```

This uses the `dotnet store` command to create a local store of NuGet dependencies and an manifest file. It then zips up that local directory and creates a Lambda layer from it and uploads the manifest to S3. 

If you were using the `dotnet lambda deploy-serverless` or `dotnet lambda package-ci` command to deploy you could then update your CloudFormation template to add the arn for the layer on each of your functions. Then during the publishing it would download the manifest from S3 and pass that into the `dotnet publish` command to exclude dlls that are in the Lambda layer.

Since you are using SAM you need to pass in the layer arn into the underlying `dotnet lambda package` command does. This can be done by creating a JSON file called `aws-lambda-tools-defaults.json` in the Function directory and specify the arn in it. Here is an example of how I did it.
```
{
    "region" : "us-west-2",
    "function-layers" : "arn:aws:lambda:us-west-2:<account-id>:layer:lambda-layer-test:2"
}
```

The underlying `dotnet lambda package` command that SAM does will pick up the layer and pass in the manifest into the `dotnet publish` command it does.

When you run SAM build you will see a warning message to set the environment variable `DOTNET_SHARED_STORE` to `/opt/dotnetcore/store/`. This is critical to make sure your CloudFormation template sets this environment variable. Otherwise when the function is deploy the .NET runtime won't know how to find the assemblies from the layer. The `dotnet lambda serverless` and `dotnet lambda package-ci` commands add this environment variable automatically.


This blog post gives some more background .NET Lambda layers
https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/

**Comment by mildaniel** [comment]
Thanks @normj for providing a detailed explanation. Please let us know if you have anymore questions @samprakos.

**Comment by hnnasit** [comment]
Thanks for the detailed explanation @normj. Closing this issue, feel free to open a new issue if you have any further questions/concerns @samprakos.
