### ISSUE TITLE
Bug: Help information of `sam package` includes `--resolve-image-repos`

### ISSUE THREAD

**Issue by ginglis13** [aws/aws-sam-cli#5424]
### Description:

`sam package` states one of following options is required : '--image-repository', '--image-repositories', or '--resolve-image-repos'. `sam package --resolve-image-repos` fails with `No such option`

### Steps to reproduce:

1. Create a Hello World Example app with `sam init`
2. `sam build`
3. `sam package`
4. observe help message, attempt again with missing options:
5. `sam package --resolve-image-repos`

### Observed result:
```
➜  TEST_APP git:(sam-demo) ✗ sam package
Usage: sam package [OPTIONS]
Try 'sam package -h' for help.

Error: Missing option '--image-repository', '--image-repositories', or '--resolve-image-repos'
➜  TEST_APP git:(sam-demo) ✗ sam package --resolve-image-repos
Usage: sam package [OPTIONS]
Try 'sam package -h' for help.

Error: No such option: --resolve-image-repos (Possible options: --image-repositories, --image-repository, --resolve-s3)
```

### Expected result:

I expected to either 

1. Not see `--resolve-image-repos` stated as a missing option OR
6. `--resolve-image-repos` to work

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Darwin bcd0741845e8 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
7. `sam --version`: SAM CLI, version 1.88.0
8. AWS region: us-west-2

**Comment by hnnasit** [comment]
Hi @ginglis13, thanks for opening the issue. I agree, the error message is misleading since `--resolve-image-repos` option is not supported for `sam package`. This is the [code](https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/cli_validation/image_repository_validation.py#L18-L94) which does the validation for `sam deploy` and `sam package`. Marking this as a bug to fix the error message.
