### ISSUE TITLE
AppSync support

### ISSUE THREAD

**Issue by gnemtsov** [aws/aws-sam-cli#551]
As far as I can see for now there is no AppSync support. It will be nice to be able to test GraphQL queries locally with local lambda as data sources. Are there any plans to implement it? What is the best option for now for developing AppSync applications? Setup local apollo server and try to connect it with local lambdas? Appreciate any advice or thoughts about that.

**Comment by ZhuangER** [comment]
For me, I usually write AppSync templates to invoke my lambda function. So for testing AppSync, I just test my lambda function locally and whether template pass parameter to lambda correctly with AppSync's UI.

**Comment by gnemtsov** [comment]
I've built a Node.js script, which works like local AppSync: [appsync-local.js](https://github.com/gnemtsov/ab-app2/blob/master/backend/appsync-local.js). This script is a part of a small serverless boilerplate AppSync application. It uses [JS-YAML](https://github.com/nodeca/js-yaml) and [Velocityjs](https://github.com/shepherdwind/velocity.js) to read definitions and velocity mapping templates from CloudFormation template and GraphQL Schema definition. Then it creates Apollo Server instance, to resolve GraphQL queries and mutations, and call local Lambda endpoint. 

It's a bit hacky. It won't execute velocity functions. But it works great if you don't put much logic into mapping templates. Subscriptions are not fully supported yet, but I am going to fix that. 

I hope my script will help someone to develop AppSync apps locally until aws-sam-cli starts to officially support AppSync.

**Comment by MiMo42** [comment]
+1

**Comment by mdrewt** [comment]
+1

**Comment by alejandrocorrea** [comment]
My question is, what happens when I have several lambdas in different languages ​​running locally whit sam, and I want to integrate them with appsync or amplify locally to test its operation with graphQL and its resolovers, without having to add api gateway. how do i do it?

**Comment by eerenwong** [comment]
+1

**Comment by bramkoot** [comment]
+1

**Comment by hoangnguyenasnet** [comment]
+1

**Comment by bramkoot** [comment]
Based on same experience at a client with a NodeJS script based on the one @gnemtsov linked, I started to work on this feature within some strict boundaries. Current state can be viewed at my [fork](https://github.com/bramkoot/aws-sam-cli) repo. 

The version I'm working on doesn't support subscriptions nor does it support Velocity templates, it basically works for Direct Lambda Resolvers. This is a version that I personally would use a lot, to locally test frontends with non-released backends that use AppSync. 

Is the SAM team open to a PR for this feature? I'll work on some tests and tidying up the codebase in the coming week so hopefully I can send in some first version in a week or so.

**Comment by rpstreef** [comment]
does anyone at AWS listen to the community? There's a development effort going on for appsync, but websockets have by far te majority vote on the issue list. Perhaps some communication can help here.

**Comment by rjmackay** [comment]
Any update on this? There's an open PR to add this functionality but it doesn't look like anyone has review this it at all?

**Comment by revmischa** [comment]
I would really love this feature so I can do local development. My use case is CDK and [prisma-appsync](https://prisma-appsync.vercel.app/).

The local development story for serverless CDK apps is the biggest drawback to that development platform right now IMHO.

**Comment by praneetap** [comment]
@rjmackay @revmischa @MiMo42 @bramkoot @y4h2 @es50678 @hoangnguyencong-agilityio @mdrewt @gnemtsov @eerenwong 
Thanks for your interest in this feature. We are hesitant to merge this today because with the current resources we would not be able to commit to maintaining this feature in the long run - maintain feature parity and fix issues with the implementation in a timely manner. Given the reaction we can see that this is important to the community and we recommend one of the two alternatives - 

1. We highly recommend you to use SAM Accelerate to test this in your development environment in the cloud. Here is a helpful [video](https://youtu.be/syHwvb_P4JM) to learn more about it, and here is the [installation instructions](https://github.com/aws/aws-sam-cli/wiki/How-to-Start-Using-sam-sync) for the beta version. Please let us know if this helps with your testing needs.
2. If testing in the cloud is not an option for you, we are considering adding plugin support if there is enough interest. Upvote and comment on this [tracking issue](https://github.com/aws/aws-sam-cli/issues/3265), if building this as a plugin would be something you would be interested in instead.

**Comment by jfuss** [comment]
Thank you for the interest. We are still exploring a Plugin based solution for local development to allow the community to enable/extend features like this. Give that, we are closing this in favor of the Plugins tracking issue: https://github.com/aws/aws-sam-cli/issues/3265
