### ISSUE TITLE
Local SSM Parameter Store

### ISSUE THREAD

**Issue by Dunedan** [aws/aws-sam-cli#616]
We're making heavy use of the SSM Parameter Store to manage configuration parameters for our Lambda functions. For testing we use environment variables to shadow the parameters from SSM, so we don't have to do calls to SSM when testing.

Unfortunately that doesn't work with SAM CLI, as it only allows overriding environment variables, which are actual environment variables defined for the Lambda function in the SAM template. While that's fine, it prevents us from using SAM CLI, as we'd need real calls to the SSM Parameter Store.

Any suggestion how to solve that problem? Are there any plans of integrating parameter store functionality for parameters defined in the CloudFormation template  in SAM CLI?

~P.S.: Slightly off-topic, but the invitation-process for #samdev doesn't work  for me. I tried different browsers and e-mail addresses, but never received an e-mail.~ Received an invitation in the meanwhile. Seems like they're sent out in batches.

**Comment by jfuss** [comment]
@Dunedan How do you see these interactions working locally? Those Parameters are stored in SSM and therefore your Lambda function would have to call the service to get the parameters during runtime, right? That would mean SAM CLI would have to mimic (yet another) service. Mimicking has lots of concerns for me: How do we keep this updated with the service? What is the fidelity of this locally? Do we support secrets? 

Instead, I would like to understand if having a 'dev' SSM Parameter Store where you can hold these values (in the cloud) and then use the CLI as you normally would. We allow credentials to be placed into the local runtime. This allows you full control over this instead of something local that may or may not fit your needs.

I would love to explore this though and see how you envision something like this and how it would work within SAM CLI.

I am going to label this with `stage/needs-feedback` and get more feedback from the community here.

On your P.S. note: Glad you finally got it. Yes, they are done in batches and we apologize on the long pull there. We are working towards making this faster for customers.

**Comment by Dunedan** [comment]
Our main motivation to not use "dev" parameters in the real SSM Parameter Store is that we would like to be able to run everything without the need of having network connectivity or AWS credentials available (aside from initially fetching the docker images of course). With https://github.com/awslabs/serverless-application-model/pull/543 the only problem left for us are the SSM parameters. Our current solution just uses environment variables and only fetches parameters from SSM Parameter Store if they're not present as environment variables. As environment we use some kind custom-built API Gateway & Lambda emulation, which predates SAM CLI, but would like to use SAM CLI in future of course.
If possible we'd simply continue to use the solution with environment variables we currently use, but we understand that that's not possible with the current implementation in SAM CLI, which makes perfect sense btw.

The most obvious solution for me would be first-class support of a project which provides AWS services locally (like discussed for `localstack` in #92), as that would solve the problem not only for SSM, but for other frequently used AWS services as well and would keep the current scope of SAM CLI. We're open to different solutions as well of course.

**Comment by sanathkr** [comment]
In your template, can you use set the type of CFN parameter to SSM ([docs)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types)?

This will remove the need for custom logic. And, you can use SAM CLI's default mechanics of overriding parameters (pending #657) to override SSM parameters locally. Does this fit your workflow?

**Comment by Dunedan** [comment]
It doesn't really fit our use case, but I'm starting to believe that we have a pretty exotic one. :smile:

We introduced the use of the SSM Parameter Store back in the days when they weren't "globals" yet and when we were still limited to 50KB SAM templates, as a measure to reduce the template size: Instead of defining the parameters as environment variables for each and every AWS Lambda function we defined them once as SSM Parameters and then fetched them in the AWS Lambda functions when needed. Thanks to "globals" that's not really necessary anymore (unless the size of parameter for a function exceeds 4KB), so we should probably simply move from using SSM Parameter Store to use "globals" instead for parameters defined in the same template. For parameters defined somewhere else your proposed solution would be the way to go I guess, but does end up passing them as environment variable to the AWS Lambda function as well, right?

**Comment by notbrain** [comment]
We also have a bunch of SSM::Parameters that we use to store credentials, passed to Lambdas via environment variables. Template looks like this:

```
DatabaseUsername:
  Type: AWS::SSM::Parameter::Value<String>
  Default: DatabaseUsername

Globals:
  Function:
    Environment:
      Variables:
        DB_USERNAME: !Ref DatabaseUsername
```

Lambda code 

```
// this gets set to "DatabaseUsername"
const DB_USERNAME = process.env.DB_USERNAME || 'postgres'
```

The issue arises because sam cli will use the default value or the !Ref'd parameter name (`DatabaseUsername`) as the _value_ of the variable, instead of seeing that it's a `SSM::Parameter::Value<String>` and knowing that's a label instead of a value.

Would be better if we could set sam cli to just be "local only" and to set any `SSM::Parameter::Value<String>` "lookup" parameters to empty. 

Or is there a better way to force sam cli to not pick a value like this?

**Comment by jfuss** [comment]
Currently we have no plans to support a Local SSM Parameter Store. Instead, you can use `--env-vars` option on SAM CLI to pass values to the running function.

Closing
