### ISSUE TITLE
Bug: Changing parameters-override when running `sam sync` does not force update

### ISSUE THREAD

**Issue by GeeWee** [aws/aws-sam-cli#6172]
### Description:

When I run e.g. `sam sync --watch --parameter-overrides "MYVAR=foo1"` the environment variables do not update in my lambda.

However if I edit `template.yml`, the variables are updated

### Steps to reproduce:

Run
`sam sync --watch --parameter-overrides "MYVAR=foo1"`
Have the parameter passed to an environment variable.
See the env variable is `foo1`

Without touching anything, run:
`sam sync --watch --parameter-overrides "MYVAR=foo2"`
Run the lambda, see the value is still `foo1`

Now touch the file, and either re-run the command or leave it running, re-execute the lambda, and see the value is now properly changed.

Cannot provide debug logs as I hit the github comment length limit.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.99.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-14.0-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by moelasmar** [comment]
Thanks @GeeWee for raising this issue. I will investigate it and update you.

**Comment by moelasmar** [comment]
I verified this issue, the root cause of this problem is in SAM CLI logic, we compared the local template file, and the deployed stack template to decide if we should update the infra or not (check [this snippet](https://github.com/aws/aws-sam-cli/blob/111952592ae9d236c1abf28a8b75725aa1e5bcbd/samcli/lib/sync/infra_sync_executor.py#L219C2-L335)), and we did not include the stack parameters in the comparison, I need to check if this was decided or we just missed it.

For now to resolve this problem you can add `--no-skip-deploy-sync` the flag to the `sam sync` command to force updating the infrastructure.
