### ISSUE TITLE
Bug: sam build is warning about missing BuildArchitecture in a layer when I don't have one.

### ISSUE THREAD

**Issue by mew1033** [aws/aws-sam-cli#6444]
### Description:
I have a template that defines a `AWS::Serverless::Function` resource. It has a `Layers` section:
```yaml
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:45
```
When I `sam build` the template, it gives me the following warning 3 times:

`WARNING: No BuildArchitecture specifed in Layer `None` Metadata. Defaulting to x86_64.`

Removing the layers section makes the warning go away.

I don't think the warning causes any issues, but it doesn't seem like it should be there.

### Observed result:
2023-12-13 15:26:27,691 | WARNING: No BuildArchitecture specifed in Layer `None` Metadata. Defaulting to x86_64.                                                                                                                                                                                  

### Expected result:
No warning

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04 (in WSL)
2. `sam --version`: 1.105.0
3. AWS region: 

```
{
  "version": "1.105.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.7",
    "aws_cdk": "Not available",
    "terraform": "1.6.5"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by hnnasit** [comment]
Hi @mew1033, thanks for reporting the issue, marking this as a UX bug.

**Comment by jojo786** [comment]
Also getting this warning when using LambdaAdapterLayer

**Comment by jim-meyer** [comment]
Also note that the warning text is misleading. It refers to `BuildArchitecture` but looking at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-architectures and https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html I see no mention of a field named `BuildArchitecture`. I do see a field named `Architectures` for AWS::Serverless::Function  and `CompatibleArchitectures` for AWS::Serverless::LayerVersion, but no `BuildArchitecture`.
I tried explicitly defining `Architectures` and `CompatibleArchitectures` in my SAM template file but the warning still occurs.

**Comment by efremsternbach** [comment]
I am observing this same problem with sam versions 1.104 and 1.105. Version 1.103 works just fine

**Comment by major-mayer** [comment]
The BuildArchitecture needs to be specified in the `Metadata` section: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html
However, this warning is not really necessary when the user just wants to copy the existing content from the `ContentUri` section to the build folder.

**Comment by efremsternbach** [comment]
The confusion for myself and others is likely that the main documentation for LayerVersion does not explicitly show Metadata as a field for the AWS::Serverless::LayerVersion type.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html

In addition this didn't used to be necessary. For sam 1.103 and earlier no errors were indicated. Everything worked previously by just specifying CompatibleArchitectures. The new requirements are confusing since I'm just using python anyway. Seems like I have to specify the platform twice because of the new rules.

**Comment by efremsternbach** [comment]
I need to follow up on my comment.

In my layer I am using pure python code so it seems kind of ridiculous to specify a BuildArchitecture. I specify that my layer is compatible with x86_64 and arm64 since I don't want to have separate layers for each architecture. I try to use arm64 where possible but occasionally there are modules that don't seem to be compatible so I need to run my Lambda on x86_64.

What am I supposed to specify for BuildArchitecture? Unlike CompatibleArchitectures there is no way to specify more than one architecture. I don't bundle the modules in the layer in order to maintain an architecture neutral layer (my requirements.txt file is empty).

This seems poorly thought out to me. It also breaks a lot of code that had been working perfectly up to sam 1.103.

For code that doesn't actually _have_ an architecture this is a big problem. Is there someone to contact at AWS to make these points?

**Comment by efremsternbach** [comment]
Trying to work through this but now getting

`WARNING: No BuildArchitecture specifed in Layer `None` Metadata. Defaulting to x86_64`

which makes no damn sense. There are no unnamed layers in my code. 

I thought it might be that I need to specify BuildArchitecture for the Lambdas in my application but I'm getting this warning 6 times when I only have 4 Lambas in that application. I have no clue what this is complaining about.

Sorry if it offends anyone but this is a disaster. Much pain for zero gain. It is truly worrisome.

**Comment by shanecandoit** [comment]
This also affects `sam --version`: 1.106.0
