### ISSUE TITLE
Bug: Breaking change on sam 1.110 with NodeJs14

### ISSUE THREAD

**Issue by atresca-globant** [aws/aws-sam-cli#6731]
### Description:
Our Codebuild started failing 3 hours ago with the new sam version 1.110. Was working fine with version 1.109. we will migrate to Node20 but we are not there yet.

Throws this error:

Error: 'nodejs14.x' does not have a supported builder
--
314 | Traceback:
315 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/click/core.py", line 1078, in main

![image](https://github.com/aws/aws-sam-cli/assets/72890641/270c2aed-ed3b-42c5-8dd8-ba327757b782)

### Expected result:

Run the sam build correctly with Nodejs 14

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.110
3. AWS region:  us-east-1b

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Hi, Lambda no longer supports updates to Node.js 14 based functions (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy), which is why SAM CLI has removed support for this runtime with this latest version. While this is technically a breaking change, this is following the guidance from Lambda and migrating to a newer supported runtime should be the path forward.

**Comment by hnnasit** [comment]
Closing this issue as this is expected behavior due to runtime deprecation.
