### ISSUE TITLE
[Feature Request] Cognito Offline Testing

### ISSUE THREAD

**Issue by oleersoy** [aws/aws-sam-cli#697]
Just curious whether SAM will support cognito offline testing?  Pasting in some links to the same feature request in various other forums:

- https://github.com/localstack/localstack/issues/26
- https://stackoverflow.com/questions/41633800/use-cognito-locally-offline
- https://stackoverflow.com/questions/51719765/invoke-lambda-function-without-authorization-on-local-serverless-offline-environ

**Comment by jhechtf** [comment]
Has there been any headway on this?

**Comment by praneetap** [comment]
@jhechtf @oleersoy 
Thanks for your interest in this feature. We are hesitant to merge this today because with the current resources we would not be able to commit to maintaining this feature in the long run - maintain feature parity and fix issues with the implementation in a timely manner. Given the reaction we can see that this is important to the community and we recommend one of the two alternatives - 

1. We highly recommend you to use SAM Accelerate to test this in your development environment in the cloud. Here is a helpful [video](https://youtu.be/syHwvb_P4JM) to learn more about it, and here is the [installation instructions](https://github.com/aws/aws-sam-cli/wiki/How-to-Start-Using-sam-sync) for the beta version. Please let us know if this helps with your testing needs.
2. If testing in the cloud is not an option for you, we are considering adding plugin support if there is enough interest. Upvote and comment on this [tracking issue](https://github.com/aws/aws-sam-cli/issues/3265), if building this as a plugin would be something you would be interested in instead.

**Comment by jhechtf** [comment]
Well then that's unfortunate. I'll likely have to stop using SAM because of this.

**Comment by jfuss** [comment]
Thank you for the interest. We are still exploring a Plugin based solution for local development to allow the community to enable/extend features like this. Give that, we are closing this in favor of the Plugins tracking issue: https://github.com/aws/aws-sam-cli/issues/3265
