### ISSUE TITLE
Feature request: Support publishing SAM template to SAR that leverages an existing macro

### ISSUE THREAD

**Issue by ShanmugapriyanSP** [aws/aws-sam-cli#7231]
### Describe your idea/feature/enhancement

The Serverless Application Repository (SAR) should support the use of custom macros within AWS Serverless Application Model (SAM) templates. Currently, SAR does not support the usage of existing macros which limits the flexibility and customization available to users deploying serverless applications.

When we attempt to publish the SAM template using either `aws serverlessrepo create-application` or `sam publish`, we encounter the following error:
`Error: Resource with name [Transform] is invalid. Provided Transform ['AWS::Serverless-2016-10-31', 'MyMacro'] is unsupported. Please use one of the following: ['AWS::Serverless-2016-10-31']`

### Use Case

We need to transform SAM templates to meet specific requirements that are unique to our operational needs and workflows. Custom macros allow us to automate and enforce these transformations, ensuring consistency, compliance, and efficiency. For instance, we may need to include custom resource definitions or apply specific configuration settings by using the parameter overrides provided by the user. We want to centralise and use the code across our AWS child accounts by leveraging SAR.

### Proposal

Ensure that SAR can seamlessly integrate with the existing macro functionality provided by SAM, allowing users to leverage their current macro implementations without modifications.

Please redirect me to the right repo if the above feature request is irrelevant to sam-cli.  Thanks in advance.

**Comment by ShanmugapriyanSP** [comment]
There is an internal backlog tracking this feature request in Cloudformation. Hence, closing this feature request.
https://github.com/aws/aws-cli/issues/8786

**Comment by dtcaciuc-ggs** [comment]
@ShanmugapriyanSP I would like to add one more voice to the feature request.

Our use case is publishing applications to SAR with [DataDog Lambda Extension](https://docs.datadoghq.com/serverless/aws_lambda/installation/python/?tab=awssam) which is now the recommended way to connect SAM applications with DataDog. The SAM macro is the best way to integrate it into the app since

* Wrapping each lambda manually and adding policies is too intrusive for development
* Instrumenting deployed applications with DataDog CLI is too intrusive for deployment

Thank you,
