### ISSUE TITLE
Publish Docker image of AWS SAM CLI 

### ISSUE THREAD

**Issue by sanathkr** [aws/aws-sam-cli#804]
**Description:**
Feature request from the [Twitter thread](https://twitter.com/clare_liguori/status/1066546445451329536). Publishing our own docker image for SAM CLI can help customers use it without installing separately on a CI/CD pipeline or locally. They can do `docker run sam-cli-image deploy`. Docker-in-Docker will be needed to enable `sam local` commands. But Docker images will certainly be another good distribution mechanism.

**Comment by medinarrior** [comment]
I use something like this:

```
FROM alpine:3.8

ENV LANG C.UTF-8

RUN apk add --no-cache python py-pip && \
    apk add --no-cache gcc python-dev musl-dev && \
    pip --disable-pip-version-check install \
        boto3 botocore awscli aws-sam-cli && \
    apk -v --purge --no-cache del gcc python-dev musl-dev

RUN apk add --no-cache docker bash
```

**Comment by jkodroff** [comment]
Considering that many (most? well, me at least...) folks will be using CodeBuild as their starting point for deploying apps with SAM, I think this would do a lot to smooth out onboarding with SAM.

**Comment by RickC37** [comment]
Are there any updates to such an official image?

All the images I created so far are in my POV too heavy (190 to 230 MB).
The issue is that I have to 
- install python 
  - to install the sam-cli
  - install the aws cli to get the sam-cli working
- and nodejs for my app itself

The result is a quiet heavy image.

It would be really cool if AWS could provide an small, alpine based, docker image with only the sam-cli. 

Depending on the app the user would only need to install the required runtime (in my case nodejs)

**Comment by red8888** [comment]
could you also publish an image per language? most modern CI/CD systems run builds inside of containers so this would prevent the need for docker in docker- you could just get the right sam image for your language

I assume you already have an image per language because of the  --use-container switch right? wouldnt you just have to add the sam cli to those images if its not in there already?

**Comment by sriram-mv** [comment]
https://github.com/aws/aws-sam-cli/tree/develop/build-image-src showcases the build images which have SAM CLI installed on them and how the `Dockerfiles` are setup.

They can be used as docker images per runtime with SAM CLI installed on them. For eg: https://hub.docker.com/r/amazon/aws-sam-cli-build-image-python3.8
https://gallery.ecr.aws/sam/build-python3.8
