### ISSUE TITLE
Websocket Support for API Gateway

### ISSUE THREAD

**Issue by nicosuave** [aws/aws-sam-cli#896]
### Describe your idea/feature/enhancement

As per the [announcement](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/) of WebSocket support in API Gateway, adding WebSocket support to SAM would facilitate local development.

### Proposal

Add WebSocket support to API Gateway functionality.

This may be entirely out of scope of the SAM project, but came to mind when initially exploring API Gateway with WebSocket support.

**Comment by abbottdev** [comment]
I think this would be extremely useful, if you're using the websocket endpoints as a consumer and not http then you're not testing what you're deploying. 👍

**Comment by redtopia** [comment]
I just started researching API Gateway Websockets and was about to dive into some test code. I was planning to do some testing using HTTP endpoints, but now I'm wondering if this is even possible. Any ideas?

**Comment by alexandrecanuto** [comment]
I'd love to see that as well.

**Comment by kauphylover** [comment]
We'd love to see this supported in SAM asap.

**Comment by virtuoushub** [comment]
It looks like it is? https://github.com/aws-samples/simple-websockets-chat-app

See: https://github.com/aws-samples/simple-websockets-chat-app/blob/master/template.yaml#L20-L25

**Comment by redtopia** [comment]
@virtuoushub I'm not 100% sure, but I think that can only be packaged and deployed using the sam cli, but not actually run.

**Comment by virtuoushub** [comment]
@redtopia ah, I think you are correct. I have successfully packaged and deployed; but running locally I have not tested. Thanks for clarifying.

**Comment by kellengreen** [comment]
That example is only for packaging and deploying. API Gateway websocket support for localhost is still lacking in SAM.

**Comment by 0num4** [comment]
I want this. ❤️

**Comment by timveletta** [comment]
👍

**Comment by anhdt-eas** [comment]
Please help asap.

**Comment by thomasrepnik** [comment]
Would love to see this feature, because my application relies heavily on websockets. This would make the local development/testing much easier.

**Comment by goldsam** [comment]
This is a blocker for my company

**Comment by mike-tedford** [comment]
We will need this for local development on our new application which may use web sockets.  Please provide an update when one is available

**Comment by M-Imtiaz** [comment]
+1
Any progress on this proposal?

**Comment by agarbutt** [comment]
This continues to be a big gap in this tooling. Yes, it seems that engineers can make do by creating a `test` stage. However, it really makes testing a bit more of a challenge, as developers, need to deploy their stacks to an account prior to testing.  I would prefer to leverage a continuous build, test, integrate, deploy pipeline to keep my feedback cycles short and quick. The lack of support within the `sam` tool to execute a lambda function via a `wss://` or `ws://` local endpoint is prohibitive.

**Comment by 592da** [comment]
any progress ?

**Comment by abbottdev** [comment]
Can we get an update here?

**Comment by v-y-a-s** [comment]
I think this would really help. Also, there is no way to test custom authorizer locally. 

`  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect # authorizers are only for connect routes
          authorizer:
            name: auth
            identitySource:
              - 'route.request.header.Auth'
`

Having the auth function deployed, the checks do happen, but there is now way to test it locally as such. Took me a while to figure this out.

**Comment by djdenv** [comment]
Following. Would really be ideal to have this feature in SAM...

**Comment by MatteoGioioso** [comment]
Any update on this?

**Comment by elembie** [comment]
+1 Following for an update

**Comment by mwalker638** [comment]
+1 - would like to see when released.

**Comment by barmag** [comment]
+1 I hope this is implemented soon. My use case is end-to-end testing of asynchronous application

**Comment by JohnRudolfLewis** [comment]
+1 Please add this feature

**Comment by danballance** [comment]
+1 this feature would be extremely useful.

**Comment by misk0** [comment]
I'm willing to help to develop this part but I don't think I can do it by myself. If anyone else is willing to help maybe we can do something..

**Comment by heretogo** [comment]
+1 Following.

**Comment by jduffy7** [comment]
+1 Also need this.

**Comment by danballance** [comment]
@misk0 I would also be willing to help although it could only be in a supporting role. I don't understand enough about how the local services are set up to be able to do this work independently.

**Comment by sarpdoruk** [comment]
+1 Just to raise awareness. People need this, it is impossible to test websockets locally.

**Comment by hugopakula** [comment]
+1 for this addition to SAM, it's been 2 years since this feature request and still no solution from AWS for people working with websockets.

**Comment by dtelaroli** [comment]
+1

**Comment by pyohei** [comment]
+1

**Comment by Borduhh** [comment]
+1

**Comment by Globebyte** [comment]
+1

**Comment by misk0** [comment]
Hi, I would like to develop this feature. I already read developer and contributing guide (also other links and document available in repo) and I have some ideas but I would like to talk with some core team member to get right directions. How can I get in touch with someone? AWS Slack invitation unfortunately doesn't work. @jfuss @sanathkr @sriram-mv @awood45 
Thanks

**Comment by DominusVilicus** [comment]
Bump

**Comment by stevenlafl** [comment]
+1

**Comment by Shapes** [comment]
+1

**Comment by kewur** [comment]
are there any workarounds we can employ to test this locally? I have other services that depends on me triggering from these lambdas.

**Comment by boblund** [comment]
+1 on SAM support for websocket. For a work around, check out [aws-lambda-ws-server](https://github.com/JamesKyburz/aws-lambda-ws-server). When executed locally, it wraps the route handler with a websocket server, although I have yet to try it in AWS.

**Comment by michalpaukert** [comment]
+1

**Comment by pharzath** [comment]
+1 Following.

**Comment by MrZakos** [comment]
+1 Following.

**Comment by rpstreef** [comment]
This is already been proposed 2 years ago, why doesn't this have any official response by now or at least a roadmap?

**Comment by boblund** [comment]
I've put together some node.js software that helped me address the lack of websocket support in SAM. First is a websocket server that wraps AWS backend websocket route integrations. With this, I can run my AWS serverless websocket app on my local machine. Second, I have a trivial wrapper for postToConnection so that apigwApi.postToConnection() is called when the backend integration is on AWS or a local postToConnection() is called when running locally.

This is all a bit of a hack at this point but I'm using it successfully. I'm still working through normalizing 5xx status returbs between the two environments.

I can spend some time tidying it up as a githup repo if there is any interest.

**Comment by misk0** [comment]
I think in case of SAM everything should be based on Python and flask framework but I wasn't able to contact anyone from team to get more explanation.  I'm still interested to work on this but it looks like a huge bite. I'm also wondering why none else started to work on this.

**Comment by goldsam** [comment]
The lack of any response on this as well as other issues is destroying my company's trust in Amazon.

**Comment by rpstreef** [comment]
@jfuss you seem to be one of the people committing regularly to AWS repo's. Can some action be undertaken to get this on a roadmap and developed. This is now lingering for 2 years, it's one of the top voted features for this product.

**Comment by afukui** [comment]
+1

**Comment by diegosasw** [comment]
After a few hours reading about API Gateway and running some tests, I've just found out I'll be unable to test API Gateway websockets locally.

Does anybody have any workaround?

I am using the AWS Runtime Interface Emulator to run lambdas locally for a conteinerized .NET 5 api. I was hoping I could run a gateway locally to test the lambda function as per https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/25

Assuming this is not possible because there's still not support in SAM CLI, how do you guys usually test these kind of scenarios locally? Does anybody know how does an event coming from API Gateway websocket towards a lambda function look like? At least with that I could skip the Api Gateway part and simply run a 
```
curl -vX POST http://localhost:9000/2015-03-31/functions/function/invocations -d @test_request.json --header "Content-Type: application/json"
```
to pass the websocket event as a json.

Any update or workaround here would be appreciated!

**Comment by Borduhh** [comment]
> After a few hours reading about API Gateway and running some tests, I've just found out I'll be unable to test API Gateway websockets locally :(
> 
> Does anybody have any workaround?
> 
> I am using the AWS Runtime Interface Emulator to run lambdas locally for a conteinerized .NET 5 api. I was hoping I could run a gateway locally to test the lambda function as per [aws/aws-lambda-runtime-interface-emulator#25](https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/25)
> 
> Assuming this is not possible because there's still not support in SAM CLI, how do you guys usually test these kind of scenarios locally? Does anybody know how does an event coming from API Gateway websocket towards a lambda function look like? At least with that I could skip the Api Gateway part and simply run a
> 
> ```
> curl -vX POST http://localhost:9000/2015-03-31/functions/function/invocations -d @test_request.json --header "Content-Type: application/json"
> ```
> 
> to pass the websocket event as a json.

We ended up setting up an actual server (*sigh). We used Docker to create a simple server using the NPM `ws` package with Express.js.

Then we can simply run the server via Docker and use the `wscat` tool to mess with it. It's been working so far.

**As a heads up as well to anyone doing IoT-related things. AWS API Gateway has a max connection time for WebSockets of 2 hours.** This ended up being a hard stop for us.

![Screen Shot 2021-02-22 at 12 07 29 PM](https://user-images.githubusercontent.com/4759596/108743245-97aec900-7506-11eb-9645-c7eba9e05a80.png)

**Comment by diegosasw** [comment]
@Borduhh building your own server is certainly a _good_ workaround, that must be painful..
Thanks for the info on time restrictions.

How did you figure out the info on how the events that arrives at the lambda look like? Haven't yet found any info on how that connection between Api Gateway WS and Lambda works..

Do you happen to have any link or event json sample on `$connect`, `$disconnect` or `sendmessage` I could use to at least mock the API Gateway? Thanks!

**Comment by Borduhh** [comment]
@diegosasw great question. So with our server, one of the neat things that it does is format the message. So the architecture is just that the IoT device connects to the WS server. Then all the server does is relay the message to API Gateway as a POST request. Then API Gateway does whatever and if a response is needed sends one back. Then the message is related to the IoT device from the WS server. It's really not that bad. Took a day or so to set up and implement (just install `express` and `ws`, then follow the instructions).

If you want to use API Gateway, I would check out the serverless framework to use(https://www.serverless.com/blog/api-gateway-websockets-example). We ultimately ended up using that to set up our initial test project. That should handle everything.

**Comment by jcarta** [comment]
+1 Looking for WebSocket support on SAM CLI for local testing

**Comment by Spankyed** [comment]
+ 1 Idek what sam is but I need my websockets local. Thanks.

**Comment by Spankyed** [comment]
+1 Idek what sam is but I need my websockets local. Thanks.

**Comment by praneetap** [comment]
Thanks for sending this pull request. We are hesitant to merge this today because with the current resources we would not be able to commit to maintaining this feature in the long run - maintain feature parity and fix issues with the implementation in a timely manner. Given the reaction we can see that this is important to the community and we recommend one of the two alternatives - 

1. We highly recommend you to use SAM Accelerate to test this in your development environment in the cloud. Here is a helpful [video](https://youtu.be/syHwvb_P4JM) to learn more about it, and here is the [installation instructions](https://github.com/aws/aws-sam-cli/wiki/How-to-Start-Using-sam-sync) for the beta version. Please let us know if this helps with your testing needs.
2. If testing in the cloud is not an option for you, we are considering adding plugin support if there is enough interest. Upvote and comment on this [tracking issue](https://github.com/aws/aws-sam-cli/issues/3265), if building this as a plugin would be something you would be interested in instead.

**Comment by theimowski** [comment]
FWIW I tried to run SAM Accelerate with the sample WS API Gateway provided by AWS team, but it failed. Details here: https://github.com/aws/aws-sam-cli/issues/3459

**Comment by lfbertucci** [comment]
+1 Following

**Comment by seanieb** [comment]
I honestly can't believe that AWS would ship WebSockets for a API gateway and have not support local development. It's tacitly saying that if you want to use AWS you'll need to have individual Accounts for development. The cost and speed implications for such a policy will result in AWS's loss of developers.

**Comment by tim-koehler** [comment]
Is there still no official or unofficial solution for local development!?

**Comment by netleafdev** [comment]
> Is there still no official or unofficial solution for local development!?

Perhaps it's because they insist on hiring only people who can pass their cringe requirements for leetcode that require a month or more of full-time studying only students or recent grads have time for, covering questions which have almost no usefulness in real-world scenarios that aren't easy to google the solution for. And, after working there for a year or two, those same people leave for more lucrative positions that also have this requirement. Before they even reach a senior level tenure for most of us, they already have enough cash to retire. It leaves the most experienced people to just stop applying after a while, hence the large number of open senior/leadership positions across FAANG, half of which are labeled urgent yet remain there for months.

Solution? Have a leetcode OR seniority/experience + project assignment & presentation/defense instead. If I were a hiring manager there, I'd hire on the spot anyone who can successfully implement this issue. Will that happen? No. So let's buckle up to be ignored.

**Comment by praneetap** [comment]
> FWIW I tried to run SAM Accelerate with the sample WS API Gateway provided by AWS team, but it failed. Details here: #3459

@theimowski This should be fixed. Please let us know if you have any more feedback for us on Accelerate!

**Comment by boblund** [comment]
I've recently created a [github repo](https://github.com/boblund/localAwsApiGw) that I use to locally test my AWS websocket work. It also supports local testing of S3 static websites and apis served by API Gateway.

**Comment by jfuss** [comment]
Thank you for the interest. To support this today in cloud, you can use sam sync. We are still exploring a Plugin based solution for local development to allow the community to enable/extend features like this. Give that, we are closing this in favor of the Plugins tracking issue: https://github.com/aws/aws-sam-cli/issues/3265

**Comment by heaven-born** [comment]
why close this ticket in favor of the Plugins tracking issue if the Plugins don't solve the issue automatically? There must be someone who will create the plugin at least. 

SAM Accelerate doesn't solve the issue for all cases either, so this ticket is basically closed with no resolution.

**Comment by goldsam** [comment]
I've been waiting over three years! REOPEN THIS TICKET!

**Comment by redtopia** [comment]
@jfuss it seems that there is interest in making this feature available. I can tell you that the *ONLY* reason why I am not using websockets on AWS is because I have no way to get them to work in local development environments.

**Comment by satokenta940** [comment]
Is it currently stagnant? I think it is necessary to support **[Websocket](https://apidog.com/blog/what-is-websocket-and-how-it-works/).**

**Comment by goldsam** [comment]
Hey AWS, Perhaps you haven't noticed, but Azure has been gaining a lot of ground on you lately. Perhaps this is part attributed their robust tooling? 😮

**Comment by brazilianbytes** [comment]
Hi everyone,

Late this month, I came here to confirm this lack of feature, but I tried to make this work until SAM fixed the issue. Please check my guide: https://medium.com/solutions-architect-rocks/java-websockets-powered-by-aws-lambda-8cd974024030

**Comment by mhodis-nix** [comment]
November 2024 - 6 years since the ticket was opened.
AWS - "Who cares?"

**Comment by godis-michael** [comment]
November 2024 - 6 years since the ticket was opened.
AWS - "Who cares?"

**Comment by luismolinamartinez** [comment]
Another year passed.

**Comment by adamdicarlo0** [comment]
New issue for better AWS visibility: https://github.com/aws/aws-sam-cli/issues/7975

Please 👍🏻 it!
