### ISSUE TITLE
Support using a non default workflow from aws-lambda-builders

### ISSUE THREAD

**Issue by jfuss** [aws/aws-sam-cli#972]
### Describe your idea/feature/enhancement

Today, `sam build` has a set up [default configuration](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/build/app_builder.py#L48) that maps a runtime to a specific builder workflow. This is great for providing a simple UX to get customers started on the right foot but doesn't provide enough flexibility to `sam build`. Two examples of this are needing to map a `provided` runtime to a Rust builder workflow or using Go Dep instead of Go Mod for the `go1.x` runtime.

### Proposal

I see three options:
1. Provide a field within `.samrc` to be able to configure functions to a given builder workflow.
2. Embed the builder workflow into the Metadata on the Resource in the template file.
3. Create another config file (maybe that belongs to aws-lambda-builders) that can be used to do the function -> builder workflow.

My opinion and proposal is to use option 1. This provide flexibility in how we map functions to builders workflows, e.g. allowing regex's or all runtimes of X will use Y builder workflow. This is also a SAM CLI specific detail and it's configuration file seems like a good spot to put this.

### Additional Details

A formal design doc going into more details of pros and cons is needed but wanted to capture thoughts in an issue first.

**Comment by billyshambrook** [comment]
This would be awesome! We currently wrap sam cli in our own python package called psam, and add our own sam build command. This is not ideal at all because we have issues with the sam cli (non) public API changing and losing out on some nice features of lambda builders.

Couple of questions would be...

How would you define the location of the external workflow package?

Will there be a official SDK to build workflows from?

Option 1 sounds the best. Option 2 would increase the verbosity of cloudformation template and option 3 would be confusing to users because they interface with sam cli and not lambda builders.

**Comment by sriram-mv** [comment]
Closing this in favor of makefile based builders, which allow for custom actions.
